### ISSUE TITLE
Cells missing in row prevents ending the document

### ISSUE THREAD

**Issue by knownasilya** [rkusa/pdfjs#101]
> stack:"Error:Cannot end row. Row has 1 columns (cells) missing\n    at Row.end (/Users/iradchenko/workspace/mapgeo/node_modules/pdfjs/lib/row.js:240:13)\n    at Table.end (/Users/iradchenko/workspace/mapgeo/node_modules/pdfjs/lib/fragment.js:71:21)\n    at Table.end (/Users/iradchenko/workspace/mapgeo/node_modules/pdfjs/lib/table.js:162:35)\n    at Document.end (/Users/iradchenko/workspace/mapgeo/node_modules/pdfjs/lib/fragment.js:71:21)\n    at Document.end (/Users/iradchenko/workspace/mapgeo/node_modules/pdfjs/lib/document.js:520:34)\n    at createMailingLabelsPdf (/Users/iradchenko/workspace/mapgeo/server/api/utils/create-mailing-labels-pdf.js:64:13)\n    at mailingLabelsRoute (/Users/iradchenko/workspace/mapgeo/server/api/routes/community/ui-dataset.js:76:25)\n    at <anonymous>"

My code looks like this:

```js
  data.forEach(function (item, index) {
    let datum = extend({}, defaults, item);
    let content = format(template, datum);

    row.cell(content, avery5160.cell);

    // Create new row after every third column (3 column setup)
    if ((index + 1) % numColumns === 0) {
      row = table.row(avery5160.row);
    }
  });

  await doc.end();
```

**Comment by rkusa** [comment]
Right, the code shouldn't be so picky. Still, the count of cells inside a row has to match the column count. But instead of throwing I'll automatically fill up the row with empty cells.
