### ISSUE TITLE
Unable to add pages of external documents of specific format - EOL expected but not found

### ISSUE THREAD

**Issue by nirber** [rkusa/pdfjs#109]
File examples:
[i-9.pdf](https://github.com/rkusa/pdfjs/files/2273301/i-9.pdf)
[fw4.pdf](https://github.com/rkusa/pdfjs/files/2273302/fw4.pdf)

```javascript
var external = new pdf.ExternalDocument(buf);
fullPdf.addPagesOf(external);
```

EOL expected but not found

**Comment by rkusa** [comment]
Thanks for sharing the failing PDFs, I'll have a look
