### ISSUE TITLE
Corrupted pdf (inconsistent)

### ISSUE THREAD

**Issue by hluz** [rkusa/pdfjs#118]
Hi @rkusa,

I'm having some intermittent problems that appear related to closing the pdf document. Here is a reduced snippet demonstrating te issue:

```javascript
export const testPDF = async function () {

  const readFile = function (f) {
    return new Promise(function (resolve, reject) {
      fs.readFile(f, (err, data) => {
        err ? reject(err) : resolve(data);
      });
    });
  }

  const tempFile = `${Random.id()}.pdf`
  const tempPath = `${os.tmpdir()}${tempFile}`;

  const doc = new pdf.Document();
  doc.pipe(fs.createWriteStream(tempPath))

  const sampleCell = doc.cell();
  sampleCell.text({fontSize: 14 }).add('headline')
  sampleCell.text({fontSize: 12 }).add('Line one')
  sampleCell.text().add('Line two')
  
  await doc.end();

  const pdfData1 = await readFile(tempPath);
  // const pdfData2 = await readFile(tempPath);

  console.log(`pdfData1 ${tempFile} length: ${pdfData1.length}`);
  // console.log(`pdfData2 ${tempFile} length: ${pdfData2.length}`);

  return true;

};
```

invoking the above function like

```javascript
    const res = await testPDF();
```
sometimes (maybe half the time) results in ```pdfData1``` having corrupted (truncated?) data.
example of invoking it six times:

```javascript
    const res1 = await testPDF();
    const res2 = await testPDF();
    const res3 = await testPDF();
    const res4 = await testPDF();
    const res5 = await testPDF();
    const res6 = await testPDF();
```
results in following console log:

```
I20190104-09:29:53.937(11)? pdfData1 6EXKAv5E2nACnDrff.pdf length: 5258
I20190104-09:29:53.941(11)? pdfData1 jfzRdCmNpC7XDkjNT.pdf length: 16
I20190104-09:29:53.944(11)? pdfData1 fyEZg7XyEg9CanpoR.pdf length: 5258
I20190104-09:29:53.946(11)? pdfData1 m2atPJS4v7B7g9iBi.pdf length: 16
I20190104-09:29:53.949(11)? pdfData1 eBoKr5zHuXyfCTc2L.pdf length: 16
I20190104-09:29:53.953(11)? pdfData1 w2pwKQAJEQwtLHvGu.pdf length: 16
```

Wen reading the same file again (as when adding the commented out lines) will always result in pdfData2 having correct data. Sample output with commented out lines added:

```
I20190104-09:29:17.490(11)? pdfData1 JAzWC7KhfprnQqAs7.pdf length: 16
I20190104-09:29:17.491(11)? pdfData2 JAzWC7KhfprnQqAs7.pdf length: 5258
I20190104-09:29:17.496(11)? pdfData1 YT9Rt97BNwW7PuhuH.pdf length: 16
I20190104-09:29:17.497(11)? pdfData2 YT9Rt97BNwW7PuhuH.pdf length: 5258
I20190104-09:29:17.501(11)? pdfData1 Hrf9H5tjEt2cTv8qo.pdf length: 5258
I20190104-09:29:17.502(11)? pdfData2 Hrf9H5tjEt2cTv8qo.pdf length: 5258
I20190104-09:29:17.505(11)? pdfData1 cx9axS5guzmh8WeMn.pdf length: 16
I20190104-09:29:17.505(11)? pdfData2 cx9axS5guzmh8WeMn.pdf length: 5258
I20190104-09:29:17.508(11)? pdfData1 fi3FeGKdnNhCi5YJv.pdf length: 5258
I20190104-09:29:17.509(11)? pdfData2 fi3FeGKdnNhCi5YJv.pdf length: 5258
I20190104-09:29:17.511(11)? pdfData1 x5jsesFbKnLMSCJHC.pdf length: 5258
I20190104-09:29:17.512(11)? pdfData2 x5jsesFbKnLMSCJHC.pdf length: 5258
```

A second question: Is there a way of getting the generated data into a variable (eg, pdfData1 above) without having to write the file into disk first?

Thanks for looking into this.

**Comment by rkusa** [comment]
> A second question: Is there a way of getting the generated data into a variable (eg, pdfData1 above) without having to write the file into disk first?

Try [`asBuffer`](https://github.com/rkusa/pdfjs/blob/5f2e68b1162ee7b37bf8193ef03cb02d3a81e4e9/docs/document.md#asbuffercallback). I have to look into the actual issue later though - thanks for reporting!

**Comment by hluz** [comment]
@rkusa , thanks for the quick reply...

> Try asBuffer.

I had a try using `asBuffer()` and it works fine when in simple pdf generation, but could not get it to work when merging pdfs and inserting a empty page when the page count after each document is odd. It hangs on `doc.next()`. Some code:

This, piping it into a `fs.createWriteStream` works fine:
```javascript
  const tempFile = `${Random.id()}.pdf`
  const tempPath = `${os.tmpdir()}${tempFile}`;

  const doc = new pdf.Document();
  doc.pipe(fs.createWriteStream(tempPath));
  const ext = new pdf.ExternalDocument(fs.readFileSync('/private/var/folders/zj/n0zwmdcs7jz4872b3h8662dc0000gn/TfqtZctBikm7oxA5c4.pdf'));
  const ext2 = new pdf.ExternalDocument(fs.readFileSync('/private/var/folders/zj/n0zwmdcs7jz4872b3h8662dc0000gn/TDyt6LpB9MePC2vPie.pdf'));

  await doc.addPagesOf(ext);
  await doc._next()
  await doc._endPage()
  if (doc._pages.length % 2 !== 0) {
    const cell = doc.cell({ paddingTop: 5 * pdf.cm })
    cell.text('** Empty Page **')
    await doc._endPage()
  }

  await doc.addPagesOf(ext2);
  await doc._next()
  await doc._endPage()
  if (doc._pages.length % 2 !== 0) {
    const cell = doc.cell({ paddingTop: 5 * pdf.cm })
    cell.text('** Empty Page **')
    await doc._endPage()
  }

  await doc.end();
```
however, attempting to use `asBuffer()` fails:

```javascript
  const doc = new pdf.Document();
  const ext = new pdf.ExternalDocument(fs.readFileSync('/private/var/folders/zj/n0zwmdcs7jz4872b3h8662dc0000gn/TfqtZctBikm7oxA5c4.pdf'));
  const ext2 = new pdf.ExternalDocument(fs.readFileSync('/private/var/folders/zj/n0zwmdcs7jz4872b3h8662dc0000gn/TDyt6LpB9MePC2vPie.pdf'));

  await doc.addPagesOf(ext);
  await doc._next()     // doc.next() does not complete  <=====
  await doc._endPage()
  if (doc._pages.length % 2 !== 0) {
    const cell = doc.cell({ paddingTop: 5 * pdf.cm })
    cell.text('** Empty Page **')
    await doc._endPage()
  }

  await doc.addPagesOf(ext2);
  await doc._next()
  await doc._endPage()
  if (doc._pages.length % 2 !== 0) {
    const cell = doc.cell({ paddingTop: 5 * pdf.cm })
    cell.text('** Empty Page **')
    await doc._endPage()
  }

  const pdfData1 = await doc.asBuffer();
```

Thanks for looking into this...

**Comment by rkusa** [comment]
Sorry, I havent found the time to look into it, by I still have it on my list

**Comment by hluz** [comment]
Thanks for the update... A few notes:

I'm currently hacking around by waiting for the piped writeStream `finish` event before attempting to read the file and it appears to work. Maybe that should be the solution, if feasible - i.e., only return from `doc.end()` when `finish` event is received? - [https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_event_finish](https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_event_finish)

Haven't found any workaround to make `asBuffer()` work and avoid having to write it to the FS.

**Comment by rkusa** [comment]
Regarding https://github.com/rkusa/pdfjs/issues/118#issuecomment-451626345
Using the internal API `await doc._next()` directly is a bit dangerous, because it is prone to creating a deadlock. Though, without testing, I think `await doc._endPage()` should be good enough for the use case (remove both `await doc._next()` lines)?

**Comment by hluz** [comment]
@rkusa, on https://github.com/rkusa/pdfjs/issues/118#issuecomment-455544981, that is basically what I'm using not to make it work. Here is my code of the relevant part:

```javascript
    const r = Random.id();
    const tempFile = `${os.tmpdir()}${r}.pdf`;
    const pdfMerge = new pdf.Document();
    const stream = fs.createWriteStream(tempFile);
    pdfMerge.pipe(stream)
    for (const id of ids) { // ids array contains the list of the ids of the documents to merge
      const r = await getFile(id);
      const ext = new pdf.ExternalDocument(Buffer.concat(r));
      await pdfMerge.addPagesOf(ext);
      await pdfMerge._next()
      await pdfMerge._endPage()
      if (pdfMerge._pages.length % 2 !== 0) { // to ensure each document always finishes with an even page number
        const cell = pdfMerge.cell({ paddingTop: 5 * pdf.cm })
        cell.text('** Page intentionally left blank. **', { fontSize: 12, font: helveticaBold })
        await pdfMerge._endPage()
      }
    }
    const closeIt = async function () {
      return new Promise(async (resolve) => {
        stream.on('finish', () => {
          resolve();
        });
        await pdfMerge.end()
      });
    }
    await closeIt();
```

I can live with that, but wondering if this should be done by pdfjs as part of ```end()```...

on https://github.com/rkusa/pdfjs/issues/118#issuecomment-455546684 (the ```asBuffer()``` issue), without ```_next()``` I can't make it work. This would be the code:

``` javascript
    const pdfMerge = new pdf.Document();
    for (const id of ids) { // ids array contains the list of the ids of the documents to merge
      const r = await getFile(id);
      const ext = new pdf.ExternalDocument(Buffer.concat(r));
      await pdfMerge.addPagesOf(ext);
      // await pdfMerge._next()
      await pdfMerge._endPage()
      if (pdfMerge._pages.length % 2 !== 0) { // to ensure each document always finishes with an even page number
        const cell = pdfMerge.cell({ paddingTop: 5 * pdf.cm })
        cell.text('** Page intentionally left blank. **', { fontSize: 12, font: helveticaBold })
        await pdfMerge._endPage()
      }
    }
    const buff = await pdfMerge.asBuffer()
```

Removing ```await pdfMerge._next()```, although it merges the documents, it does not add the empty pages. With the ```await pdfMerge._next()``` in place, it does not work.

Tanks for taking the time on this...

**Comment by rkusa** [comment]
> I can live with that, but wondering if this should be done by pdfjs as part of `end()`...

I think it makes sense, but behind an option 

> Removing `await pdfMerge._next()`, although it merges the documents, it does not add the empty pages. With the `await pdfMerge._next()` in place, it does not work.

You are right, it seems I have to relearn parts of the code I have written 😄
`pdfMerge._next()` is indeed necessary, since `pdfMerge.addPagesOf(ext);` only queues the operation, but does not execute it right away (thus, the `await` has no effect here).
The underlying issue now is that `_next` tries to write something (for the underlying reader). But if there is no consumer for the reader, the reader blocks. That is, while your example works with `doc.pipe(fs.createWriteStream('test.pdf'))`, it does not work with `await pdfMerge.asBuffer()`.

You can work around this by the following snippet:

```js
const doc = new pdf.Document();

// start reading here
const buff = new Promise((resolve, reject) => {
  const chunks = []
  doc.on('data', chunk => chunks.push(chunk))
  doc.on('end', () => resolve(Buffer.concat(chunks)))
  doc.on('error', reject)
  // this is basically the same `asBuffer` does, except we are not calling `doc.end` yet
})

// MERGE documents here

doc.end();
const pdfData = await buff;
```

I am wondering whether we should add an option to `asBuffer` to not end the document right away 🤔

**Comment by hluz** [comment]
Thanks for looking into this. Will try that workaround.

> I am wondering whether we should add an option to `asBuffer` to not end the document right away

That sounds sensible. It would be great if you could do that!

**Comment by rkusa** [comment]
Updated snippet with the commit above:

```js
const doc = new pdf.Document();

// start reading here
const buff = doc.asBuffer({end: false})

// MERGE documents here

doc.end();
const pdfData = await buff;
```

**Comment by hluz** [comment]
Works great. Thanks!
