### ISSUE TITLE
Merging of single page pdfs

### ISSUE THREAD

**Issue by adame21** [rkusa/pdfjs#131]
Hi,
I'm trying to use this package to merge single page pdfs on a nodejs server.
The documentation is very lacking and I find it very confusing to use especially since this package is both server and client side to my understanding.
Could I possibly get a starting point or know what are the relevant methods? I have the pdfs both as buffers and as actual files on a local folder.
Any help would be appreciated.
Thanks!

**Comment by rkusa** [comment]
Hi, does the following help as a starting point:

```js
const doc = new pdf.Document({
  font:    require('pdfjs/font/Helvetica'),
  padding: 10
})
doc.pipe(fs.createWriteStream('output.pdf'))

// render something onto the document

await doc.end()

**Comment by adame21** [comment]
Hi, I appreciate the answer, I ended up using something else.
Its really great of you to answer anyway. thank you.
I'll be closing this now, hopefully it will help someone in the future.
