### ISSUE TITLE
Add type definitions to font/*

### ISSUE THREAD

**Issue by zanona** [rkusa/pdfjs#132]
Currently on Typescript I cannot import

```import * as Helvetica from 'pdfjs/font/Helvetica';```

because it doesn't have a type definition. Would it be possible to add the typings for these modules so they are known to export a `pdf.Font`?

Thanks

**Comment by rkusa** [comment]
Definitely something we should have! I tried adding it, but TBH, I failed getting it work for subpaths like `pdfjs/font/Helvetica` 😬
Maybe @laedit (author of #91) knows how this would work?

**Comment by laedit** [comment]
Sorry for the late response!
I am not an expert in Typescript but I think you need to declare a module for each font, like that:

``` ts
declare module "pdfjs/font/Helvetica" { export = pdf.Font }
```` 

I will try to test it when I will get some free time.
