### ISSUE TITLE
Is it possible to overlay images on the character? 

### ISSUE THREAD

**Issue by dai-yamashita** [rkusa/pdfjs#15]
Dear @rkusa 

pdfjs very good library !!

now try invoice template .

Image that I want to create will be something like the following.

http://oss.icz.co.jp/invoice/img/about/i_img04.jpg

I want to overlay a stamp on top of Address.

will not be able like this?

**Comment by rkusa** [comment]
When adding the image after the address, set `wrap` to false and define the `x` and `y` coordinates for the image, it is also possible to overlay it on top of the address.
