### ISSUE TITLE
embedding PDFs

### ISSUE THREAD

**Issue by jsNifty** [rkusa/pdfjs#17]
Hi rkusa

I have a requirement to be able to place one or more .PDF files within a dynamically generated .PDF, in a similar fashion as you might insert an image JPEG, PNG etc... Would the current system be capable of this?

**Comment by rkusa** [comment]
Hi, I've this requirement, too. However it is not possible, yet. I am currently working on major improvements and this feature is on my list. But I've no ETA.

**Comment by jsNifty** [comment]
Thanks for your reply.  It would be a great and valued addition as at this time I cannot find a solution.

**Comment by rkusa** [comment]
@jsNifty Do you want to add whole sides from an existing PDF file, or embed PDFs like images?

**Comment by jsNifty** [comment]
It would be excellent to be able to insert PDFs like you would insert images. There could be more than one PDF to embed in any one document.

**Comment by rkusa** [comment]
I've implemented this feature in the current [dev branch](https://github.com/rkusa/pdfjs/tree/dev). However, this branch is highly unstable. After some cleanup and further testing in the next couple of days, I'll provide a test snippet for PDF embedding.

**Comment by jsNifty** [comment]
This is excellent! I look forward to working with this feature in the near future.
Thanks!!

**Comment by rkusa** [comment]
Would you mind testing the PDF embedding?

You'll have to use the dev branch. Example snippet:

```js
var pdfjs = require('./')
var path = require('path')
var fs = require('fs')

var regular = pdfjs.createTTFFont(
  fs.readFileSync(path.join(__dirname, 'test/fixtures/font/opensans/regular.ttf' ))
)

var doc = pdfjs.createDocument({
  font: regular
})

var img = pdfjs.createImage(
  fs.readFileSync(path.join(__dirname, 'logo/pdfjs.pdf' ))
)
doc.image(img)

var pdf = doc.render()
fs.writeFileSync(path.join(__dirname, 'pdf.pdf'), pdf.toString(), 'binary')
```

It is quite likely that you'll get an error. If so, I would highly appreciate if you could send me the PDF that fails.

Thanks

**Comment by jsNifty** [comment]
Hi rkusa

I will give this ago over the next day or two and let you know if there are any issues.  Sorry for getting back to you so late.

Regards

**Comment by jsNifty** [comment]
Hi rkusa

I have tried embedding a simple PDF file and this has not worked.  Can I direct mail you with the PDF somehow as it is not something I would like on the issues page.

**Comment by rkusa** [comment]
Sure: github.m@rkusa.st
Thanks

**Comment by jsNifty** [comment]
Just another question with relation to the now available feature to embed PDFs.  Is it now possible to embed a PDF as a background like you would an Image?

**Comment by rkusa** [comment]
Yes, e.g., as a background for every page:

```js
var header = doc.header()

header.image(img, {
          wrap: false,
          x: 0, y: 0,
          width: img.info.width,
          height: img.info.height
        })
```

Maybe, I'll add a simpler API in the future.
