### ISSUE TITLE
table.row cell - does not inherit font settings

### ISSUE THREAD

**Issue by thedomeffm** [rkusa/pdfjs#175]
Hi;

when I want to have a multiline table row cell, the child text block does not inherit from parent as I would expect.

As you can see in 'col2 - 2' the second row has the default text settings from the pdf, not from the table.row.
I can handle this when I again pass options to the text as you can see in 'col5 - 2'

code:
```
const tr = table.row({
        font: helveticaBold,
    });

    tr.cell('col1');
    tr.cell().text('col2 - 1,').text('col2 - 2');
    tr.cell('col3');
    tr.cell('col4');
    tr.cell().text('col5 - 1').text('col5 - 2', {
        font: helveticaBold,
        fontSize: 10,
    });

```
result:
![Screenshot_20191105_110310](https://user-images.githubusercontent.com/29406401/68198277-fec80780-ffbb-11e9-9640-fef1062bf42e.png)

**Comment by rkusa** [comment]
That is interesting! I'll look into it. Maybe the following works in the meantime:

```diff
- tr.cell().text('col2 - 1,').text('col2 - 2');
+ tr.cell().text('col2 - 1,').add('col2 - 2');
```

**Comment by rkusa** [comment]
Should be fixed on `master`, thanks again for the report!
