### ISSUE TITLE
WebWorker may not close in IE11

### ISSUE THREAD

**Issue by tqtiwvfdn** [rkusa/pdfjs#177]
While open pdfjs in IE11 with iframe，multi times。Web Worker may not close 。

like this：
![image](https://user-images.githubusercontent.com/8609832/68578034-30edd380-04ac-11ea-809f-b6ceb8d39fbd.png)

Fix it in pdf.js

```javascript
            var worker = new Worker(workerSrc);
            // IE11 下关闭iframe没有停止WebWorker
            // lijiancheng@agree.com.cn
            window.addEventListener('unload',function(){
              worker.terminate();
            });

            var messageHandler = new _message_handler.MessageHandler('main', 'worker', worker);
```

**Comment by rkusa** [comment]
Is it possible that your issue is about https://github.com/mozilla/pdf.js and not this repo here?

**Comment by tqtiwvfdn** [comment]
Ha……thank you.
