### ISSUE TITLE
Node Response output PDF file

### ISSUE THREAD

**Issue by jsNifty** [rkusa/pdfjs#18]
I am using Node.js to generate PDF documents and their content based on MySQL DB data.  However I am not sure on how to automatically open the document in the browser (not an dataURL / IFrame) and also automatically download the file.  

Previously I would have used something like the following to download and output to the browser using PDFKit:

doc.pipe(fs.createWriteStream(filename));
//  Respond to the Request with the Response (PDF File)
doc.pipe(res);
//  Close the Document
doc.end(); 

If I have missed something in the docs apologies.

**Comment by rkusa** [comment]
Stream support will be added in the near future. In the meantime:

```
res.write(new Buffer(pdf.toString(), 'binary'))
```

Does this work for you?

**Comment by jsNifty** [comment]
I have placed the following code into my page but this is not working.

 var pdf = doc.render();
            res.write(new Buffer(pdf.toString(), 'binary'));

**Comment by rkusa** [comment]
Does adding `res.set('Content-Type', 'application/pdf');` help?

**Comment by jsNifty** [comment]
Apologies I already have the headers set as below and when I tries the above code it said as much "the headers are already set".

 //  SET Variables to be Used
            var docWidth = results[0].img_width;
            var docHeight = results[0].img_height;
            var docFileName = results[0].file_name;
            
            
            // Set Some Response Headers (For i.e. Browser)
            res.statusCode = 200;
            res.setHeader('Content-type', 'application/pdf');
            res.setHeader('Access-Control-Allow-Origin', '*');
            
            //  PDF DOC GENERATION:
            var doc = new pdfjs.createDocument({
                width : docWidth,
                height: docHeight
            });
            
            var pdf = doc.render();
            
            fs.writeFile(docFileName, pdf.toString(), 'binary');
            res.write(pdf.toString(), 'binary');

**Comment by rkusa** [comment]
Ah, its `res.send(new Buffer(pdf.toString(), 'binary'))` and not `res.write`, sry ;-)

**Comment by jsNifty** [comment]
That's it!! worked perfectly 

saved a copy to server and also rendered in browser to specified width and height!!

Thanks

**Comment by rkusa** [comment]
You are welcome!
