### ISSUE TITLE
cell borders not working?

### ISSUE THREAD

**Issue by Johan-smith** [rkusa/pdfjs#180]
I have a full implementation with your library in working order with one exception: can't get (cell) properties relating to cell borders working. Not in your playground, not in my own test projects. Am using (example) ,borderTopWidth and ,borderTopColor but none of the borders are showing in any scenario. It is documented and I see these properties being referenced in your code. I must be doing something wrong, but not clear what. Can you give a working example please?

**Comment by rkusa** [comment]
I can see how this is confusing, if you are referring to cells of tables. The properties like `borderTopWidth` and `borderTopColor` only work in standalone cells outside of tables. I might have to rename them to e.g. `Box` to be more clear about the fact that they act a bit different compared to the cells of tables.

Here are some examples:

Standalone cells:
https://github.com/rkusa/pdfjs/blob/master/test/pdfs/cell/border-bottom.js
https://github.com/rkusa/pdfjs/blob/master/test/pdfs/cell/border-bottom.pdf

Table cells:
https://github.com/rkusa/pdfjs/blob/master/test/pdfs/table/border-colorful.js
https://github.com/rkusa/pdfjs/blob/master/test/pdfs/table/border-colorful.pdf

**Comment by Johan-smith** [comment]
Hi Markus,

Thank you for your quick reply. That's clear, I'll have another play. I did get some borders to show on cells inside a table after all, so I need to investigate a little more.

Great library though!

Best regards

Johan

**Comment by rkusa** [comment]
Thanks, feel free to reopen the issue if you encounter other questions 👍
