### ISSUE TITLE
Font.isFont return false, even with the default font

### ISSUE THREAD

**Issue by neurovul** [rkusa/pdfjs#182]
Hello

I have the following error when I try to create a new Document using the default font (same issue with another font): **opts.font must be set to a valid default font**

Here is my code `const doc = new pdf.Document();`

I took a look at the code and I found that `Font.isFont(this.defaultFont)` don't work really fine on my side
https://github.com/rkusa/pdfjs/blob/09f7f72c7f708681def6219b07595b56b689e4a4/lib/document.js#L58-L60

https://github.com/rkusa/pdfjs/blob/09f7f72c7f708681def6219b07595b56b689e4a4/lib/font/base.js#L4-L6

because `font instanceof Font` is false. I added `console.log(typeof font)` and I found that **type of font === object**.

Everything work well if I comment `throw new TypeError('opts.font must be set to a valid default font')`, I can create a new Document and add external pages.

I'm using PDFjs on client side, in a React app.

BR
Paul

**Comment by rkusa** [comment]
Hi,

the `opts.front` is a required option, you always have to provide one, e.g.:

```js
const doc = new pdf.Document({
  font: require('pdfjs/font/Helvetica'),
})
```

The idea behind this requirement is that you only bundle the fonts you actually use when using `pdfjs` on the client-side.

**Comment by neurovul** [comment]
Hello,

Thanks for your response.

I already tried providing the opts.font option however I have the exactly same error.
Here you can see a screenshot with the content of opts.font and you can see that **typeof opts.font === object** not **Font**:

<details>
  <summary>Click to show the screenshot</summary>

![pdfjs1](https://user-images.githubusercontent.com/25618232/71243540-d8162400-2310-11ea-889f-360abae3474a.PNG)

</details>

So as I said it throws the following error:

<details>
  <summary>Click to show the screenshots</summary>

![pdfjs3](https://user-images.githubusercontent.com/25618232/71243853-8621ce00-2311-11ea-9062-f2a363848d63.PNG)

![pdfjs4](https://user-images.githubusercontent.com/25618232/71243862-89b55500-2311-11ea-911c-4eea28173aad.PNG)

</details>

Your library perfectly work (to merge pdfs) if I comment the following lines:

<details>
  <summary>Click to show the screenshot</summary>

![pdfjs2](https://user-images.githubusercontent.com/25618232/71244074-fcbecb80-2311-11ea-904a-b80c6aca9e7c.PNG)

</details>

So I think there may is another issue than just omitting opts.font option.

BR
Paul

**Comment by rkusa** [comment]
Thanks for the additional details.

I also noticed that I forgot that [`font` has a fallback](https://github.com/rkusa/pdfjs/blob/master/lib/document.js#L53) (so my previous comment was wrong anyway).

Are you using pdfjs on the client-side, if so which bundler do you use - webpack? It sounds a bit like that the bundle has multiple different versions of `Font`, so that the `instanceof` check fails.

**Comment by neurovul** [comment]
Yes you are right, I am using pdfjs on client side and I use webpack as bundler.

**Comment by rkusa** [comment]
Should work now (released as `2.3.3`)

**Comment by rkusa** [comment]
@bflemi3 Can you try to attach a debugger to the [`isFont` check](https://github.com/rkusa/pdfjs/blob/30d357b9e09f5e50e68f35c6432d5797a86573c4/lib/font/base.js#L5-L14) and see why it isn't returning `true`?

**Comment by bflemi3** [comment]
Sorry, finally had time to get back to this. I updated the import, adding `.js` to `pdfjs/font/Helvetica.js` and it's now returning true.
