### ISSUE TITLE
Add text using op low level operations

### ISSUE THREAD

**Issue by hugodion** [rkusa/pdfjs#184]
Hi!

I tried to write some text manually using the ops without success. Is this code suppose to work?

doc.op('BT');
doc.op(1, 0, 0, 1, 10, 430, 'Tm');
doc.op(10.175, 'TL');
doc.op(0,0,0 , 'sc');
doc.op('Helvetica', 24, 'Tf');
doc.op('Text to display', 'TJ');
doc.op('ET');

Thanks in advance!

**Comment by rkusa** [comment]
Hi, yes this is supposed to work. I've quickly tested it, and it also ends up in the PDF document. However, I think your operations are not correct. I might be wrong, I haven't checked the specification for that, but I think `Tf` without a font object does not work, and `TJ` requires an array of PDF strings.

What are you trying to achieve?

**Comment by hugodion** [comment]
Hi Markus,
Yes it worked when I added the font object.
Thanks for the reply!

btw, you package is really the best for pdf generation. Very versatile and easy to work with.
