### ISSUE TITLE
e.t.a. on 0.8 version

### ISSUE THREAD

**Issue by sanderbaas** [rkusa/pdfjs#19]
Hi @rkusa ,

First of all: great lib for generating pdf's! I use it for displaying tables. I am currently using version 0.5.4, but the 0.8 version offers a lot more features. When do you think 0.8 will be a stable version? Is it a mattor of weeks or months?

**Comment by rkusa** [comment]
Hi @sanderbaas, I probably going to fix the remaining minor rendering issues at the end of this month or at some time in April. So it is a matter of up to six weeks. Thanks for asking

**Comment by rkusa** [comment]
I've increased the version to 1.0 instead of 0.8 to make the breaking API changes more clear. There is also an alpha release at NPM. I would not say that pdfjs is stable, yet, but I wouldn't declare `0.5.x` as stable, too.
