### ISSUE TITLE
lexer.isWhiteSpace is undefined

### ISSUE THREAD

**Issue by marcodafonseca** [rkusa/pdfjs#195]
We have built some services in Node.Js that use pdfjs to combine multiple pdf files into a single PDF.

However, we found a scenario today where using a certain kind of pdf (I am still unclear why some PDFs behave a little differently during the combining process) an error like the following is thrown:

> {
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "TypeError: lexer.isWhiteSpace is not a function",
  "trace": [
    "Runtime.UnhandledPromiseRejection: TypeError: lexer.isWhiteSpace is not a function",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:210:5)",
    "    at process.EventEmitter.emit (domain.js:476:20)",
    "    at processPromiseRejections (internal/process/promises.js:201:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:94:32)"
  ]
}

>

After a lot of investigation I found where the issue is being thrown. It is on line 165 of the lib/object/string.js file in pdfjs

> 165:         case lexer.isWhiteSpace(c):

> 
We then looked into the Lexer class defined in lib/parser/lexer.js only to discover that the isWhiteSpace function defined in there is static and thusly is not part of objects instantiated from this class

>   static isWhiteSpace(c) {
    return (
      c === 0x00 || // NULL
      c === 0x09 || // TAB
      c === 0x0A || // LF
      c === 0x0C || // FF
      c === 0x0D || // CR
      c === 0x20    // SP
    )
  }

> 

I figured a quick and easy fix would be adding the following to the class and will issue a Pull Request for it shortly:

> isWhiteSpace(c) {
    return Lexer.isWhiteSpace(c);
  }

> 

**EDIT**
My pull request can be found here: https://github.com/rkusa/pdfjs/pull/196

**Comment by rkusa** [comment]
Thanks a lot for digging into the cause of the error and creating a PR, highly appreciated!
