### ISSUE TITLE
PDF with header and only table, breaks table header

### ISSUE THREAD

**Issue by VijeshDatt** [rkusa/pdfjs#202]
Hi,
The bug i found was that if you have a header, footer and just a table as the body, the header of the table aligns with the document header

![image](https://user-images.githubusercontent.com/19395432/75750741-5cf5d300-5d81-11ea-8753-c7b7fa16cc32.png)

As seen by the image above.

I found that a temp solution is to add the following line between the document header and the table code:

`var cell = doc.cell({ paddingBottom: 0.5 * pdf.cm })`

Hopefully a better solution can be formed than this workaround?

**Comment by rkusa** [comment]
Thanks for the report! 🙏
Should be fixed in version `2.3.5`

**Comment by VijeshDatt** [comment]
Glad i could help, thanks for the amazing plugin 😁
