### ISSUE TITLE
Can't append certain PDFs

### ISSUE THREAD

**Issue by marcodafonseca** [rkusa/pdfjs#209]
I have just discovered a weird bug while trying to append PDFs together.

I am using the latest version of PDFjs.

My code is quite simple:
>let doc = new PDFJS.Document();
>let binary = getObjectBinary(url);
>let temp = new PDFJS.ExternalDocument(binary);
>doc.addPagesOf(temp);

This works most of the time without issue, however, with particular PDFs it throws the following error on the 3rd line above:
> Error: Invalid number: 
> 
>     at Lexer._error (...\node_modules\pdfjs\lib\parser\lexer.js:128:11)
>     at Lexer.readNumber (...\node_modules\pdfjs\lib\parser\lexer.js:156:16)
>     at Function.parse (..\node_modules\pdfjs\lib\object\object.js:42:22)
>     at parseObject (...\node_modules\pdfjs\lib\object\reference.js:128:22)
>     at PDFReference.get [as object] (...\node_modules\pdfjs\lib\object\reference.js:15:17)
>     at new ExternalDocument (...\node_modules\pdfjs\lib\external.js:19:48)
>     at Object.exports.assembleAppendToForm (...\assembler.js:156:24)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async Object.exports.handler (...\app.js:36:9)

I tried looking into the files and initially the first difference I noticed was that PDF files that failed have metadata assigned to them.
However, I have also managed to create a PDF with the same metadata assigned to it and it managed to append correctly.

I do know, to a level certainty, that all files we have found issue with were originally either Word docx files or Excel xlsx/xlsm files which were converted to PDF using Microsoft Office's "Save as PDF" functionality, but that's not to say all files undergoing this same process are currently failing, so I'm a bit stumped right now...

All files in question don't appear to be corrupted as they all work perfectly fine in any PDF viewer I have tested.

Here is an example file that is currently failing:
[TestDoc.pdf](https://github.com/rkusa/pdfjs/files/4522147/TestDoc.pdf)

As you can see there is nothing strange about it at first glance...

Any help would be greatly appreciated as this is a problem we are having in a production environment.

**Comment by rkusa** [comment]
Thanks for the report - especially for the example PDF, which made finding the issue easy! Should be fixed on master now. I'll also release a new version later today

**Comment by marcodafonseca** [comment]
Awesome! Thanks for issuing a fix so quickly :)
