### ISSUE TITLE
Cannot display JPG image with Buffer provided

### ISSUE THREAD

**Issue by telfordho** [rkusa/pdfjs#210]
I am trying embed following image to a mini project.
![image-0](https://user-images.githubusercontent.com/34391995/80441375-6b093f80-893d-11ea-9b9b-e64717c9a73e.jpg)

**Here's my setting:**
`{
  "name": "pdfjs",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/express": "^4.17.6",
    "fs-extra": "^9.0.0",
    "pdfjs": "^2.3.5",
    "ts-node": "^8.9.1",
    "typescript": "^3.8.3"
  },
  "scripts": {
    "start": "ts-node pdf.ts"
  }
}`

**I simply use fse to get the buffer, create a new row and cell, then call new pdf.Image( )**

> (async` () => {
        const doc = new pdf.Document({
              font:    require('pdfjs/font/Helvetica'),
              padding: 10
    })
> doc.cell().text('Contract Title: ')
      .add(''.padStart(1))
      .add('abc', { underline: true, fontSize: 9 })

 > try{
      const newImgsTable = doc.cell().table({ widths: [null] });
      let newImgsTableRow = newImgsTable.row({ lineHeight: 1.8 });
      let imageBuffer = await fse.readFile('./image-0.jpg');
      console.log(imageBuffer)
      newImgsTableRow.cell({ padding: 1 }).image(new pdf.Image(imageBuffer), { align: 'center' });
      doc.pageBreak();
  } catch(err) {
      console.log(err)
  }
 >  doc.pipe(fse.createWriteStream('output.pdf'))
     // render as pdf
     await doc.end()
 })()

**As a result, the Buffer can be logged and pdf successfully generated after I yarn start the node. But the Image cannot be displayed.**

`<Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 01 2c 01 2c 00 00 ff e2 0a 20 49 43 43 5f 50 52 4f 46 49 4c 45 00 01 01 00 00 0a 10 00 00 00 00 02 10 00 00 ... 669737 more bytes>`
<img width="341" alt="Screenshot 2020-04-28 at 10 56 03 AM" src="https://user-images.githubusercontent.com/34391995/80442330-3b5b3700-893f-11ea-93e6-36ae25c9019d.png">
<img width="1299" alt="Screenshot 2020-04-28 at 10 57 21 AM" src="https://user-images.githubusercontent.com/34391995/80442349-41e9ae80-893f-11ea-92dd-56dd7ae50ede.png">

**But when I test some other images, some images can be displayed and some can't. May I know what cause the issues and how to fix it?**

**Comment by rkusa** [comment]
Thanks a lot for the report! Should be fixed on master, and I'll release a new version later today.

**Comment by telfordho** [comment]
Thanks for the quick fix! ;)
