### ISSUE TITLE
Error: Invalid stream: `endstream` not found

### ISSUE THREAD

**Issue by marcodafonseca** [rkusa/pdfjs#212]
We have found another appending issue in production when appending the following file to other PDFs: [CCF12052020.pdf](https://github.com/rkusa/pdfjs/files/4621974/CCF12052020.pdf)

> Error: Invalid stream: \`endstream\` not found
    at Function.parseInner (...\node_modules\pdfjs\lib\object\object.js:112:17)
    at Function.parse (...\node_modules\pdfjs\lib\object\object.js:68:27)
    at parseObject (...\node_modules\pdfjs\lib\object\reference.js:128:22)
    at PDFReference.get [as object] (...\node_modules\pdfjs\lib\object\reference.js:15:17)
    at Function.addObjectsRecursive (...\node_modules\pdfjs\lib\parser\parser.js:61:35)
    at ...\node_modules\pdfjs\lib\parser\parser.js:82:18
    at Array.forEach (<anonymous>)
    at Function.addObjectsRecursive (...\node_modules\pdfjs\lib\parser\parser.js:81:15)
    at Function.addObjectsRecursive (...\node_modules\pdfjs\lib\parser\parser.js:77:18)
    at Function.addObjectsRecursive (...\node_modules\pdfjs\lib\parser\parser.js:68:16)

Here is a very basic rundown of how our code is working:

```
let doc = new PDFJS.Document();
// Add detail to the doc
let temp = new PDFJS.ExternalDocument(binary); // This is the binary of the document attached to this issue
doc.addPagesOf(temp);
let buffer = doc.asBuffer(); // <- this is the line the error is being thrown on
// Then we intend to save the buffer to our storage
```

As you can see our approach is very simple and this works for lots of other files. Just not sure why this particular file is giving this problem.

**Comment by rkusa** [comment]
Thanks for the report!

> Just not sure why this particular file is giving this problem.

This is because there are so many PDF generators out there that may not strictly follow the PDF specification, so it will happen once in a while that you encounter a PDF `pdfjs` cannot parse. I've updated the `pdfjs`'s parser to accept the whitespace before an `endstream` which fixes the issue for the linked PDF. I'll probably do a release later today.

**Comment by marcodafonseca** [comment]
> Thanks for the report!
> 
> > Just not sure why this particular file is giving this problem.
> 
> This is because there are so many PDF generators out there that may not strictly follow the PDF specification, so it will happen once in a while that you encounter a PDF `pdfjs` cannot parse. I've updated the `pdfjs`'s parser to accept the whitespace before an `endstream` which fixes the issue for the linked PDF. I'll probably do a release later today.

Hmmm, that is frustrating but makes perfect sense. So it was just another whitespace issue? Sigh @ whoever it was that wrote the code that put the whitespace there in that file. Thanks for the fix, @rkusa
