### ISSUE TITLE
Merge Two Page into one page

### ISSUE THREAD

**Issue by PejmanNik** [rkusa/pdfjs#219]
Hi, Thank you for your great lib.
I have tow `ExternalDocument` by adding them to the base doc. it will add 2 pages to the doc but I need a single page that continues both pages overridden.

I try developing my `write` function and register and add both page object to the doc but it doesn't change the result.

Thank you again

**Comment by rkusa** [comment]
Hi, I am not sure if I understood you.
> but I need a single page that continues both pages overridden.

What your are getting are two pages:

```
 ---
| 1 |
 ---
 ---
| 2 |
 ---
```

But what you are trying to achieve is one page that has the content of both - so basically a very long page?

```
 ---
| 1 |
| 2 |
 ---
```

**Comment by PejmanNik** [comment]
Hi, Thank you for your response,
Yes exactly.  in my case the may overload 🤐

**Comment by rkusa** [comment]
Hmm, while I am glad that I understood your use-case, I am afraid that this is currently not possible with `pdfjs` 😕

**Comment by PejmanNik** [comment]
Thank you 😁
