### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by knownasilya** [rkusa/pdfjs#22]
Just something to think about, but if you are changing the API so that they are breaking changes from 0.5, then this version should be 1.0. If you are still iterating, then release it as 1.0.0-beta.1 or something along those line. Otherwise, people will have issues if they used `^0.5.3` to install this module.

**Comment by rkusa** [comment]
Good point, but I've considered Semver, which says:

> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Also `^0.5.3` does not install anything `>0.5` - the `^` only works for `>=1.0.0`.

Thanks anyway for bringing this up :-)

**Comment by rkusa** [comment]
I've published the current version as suggested: `npm install 1.0.0-alpha.1`

**Comment by knownasilya** [comment]
Nice! :+1:

**Comment by knownasilya** [comment]
Would love at least some sort or table sizing API for 1.0. We could always rethink the API for 2.0. This is basically a deal breaker for me.
