### ISSUE TITLE
Set cursor in doc

### ISSUE THREAD

**Issue by hugodion** [rkusa/pdfjs#220]
Hi rkusa !

How can we set the cursor's y in a doc before adding doc.text ?

Thanks in advance !

**Comment by rkusa** [comment]
Hi, if you want to absolutely position text, I'd recommend to use a cell as a container instead, example: https://github.com/rkusa/pdfjs/blob/master/test/pdfs/cell/xy.js. Does this solve your use-case?

**Comment by hugodion** [comment]
Hi! I would like to have the same distance between thoses elements. I use "/n" for the moment to space the titles. If I could start the third phrase a little bit higher without using /n, that would be great. :)
![image](https://user-images.githubusercontent.com/36448889/87175467-aeb9e700-c2a6-11ea-9e28-3aae48a197b4.png)

**Comment by rkusa** [comment]
You could achieve this with a cell and a padding top:

```js
doc.cell('Est-ce ...', { paddingTop: 40 })
```

Maybe not the nicest API for such a use-case. I'll keep something like that in mind, since I guess it makes sense to have something in `doc.text()` that allows to offset the text by a specific amount.

**Comment by hugodion** [comment]
Great Thanks !
