### ISSUE TITLE
does it support RTL and Arabic language?

### ISSUE THREAD

**Issue by gkirthiv** [rkusa/pdfjs#225]
Hi @rkusa ,

does this package support RTL and Arabic language? I tried to convert a PDF using arabic contents. But it generates the PDF without the contents?

any suggestions?

![image](https://user-images.githubusercontent.com/37901258/90268259-69697600-de5f-11ea-9455-c7e93ea9d693.png)

> _the underline text contains the Arabic characters_

**Comment by rkusa** [comment]
Hi @gkirthiv, it supports UTF8 characters, which includes Arabic language characters. But the playground uses a font that does not contain such characters, so you'd have to create a PDF with your own TTF font. However, I am araid that the library does unfortunately not support RTL nor proper Arabic font shaping 😕

**Comment by gkirthiv** [comment]
Hi @rkusa 

I tried with Arabic font, but as you mentioned, but the layout is not properly shown like RTL layout. Arabic text with LTR format. 
Anyway, Thanks for  your response.

Thanks
