### ISSUE TITLE
pdf.ExternalDocument fails when loading a PDF.

### ISSUE THREAD

**Issue by wjonesusna2012** [rkusa/pdfjs#227]
![Screenshot from 2020-08-26 20-47-10](https://user-images.githubusercontent.com/44551434/91379867-302eef80-e7e9-11ea-8fed-ce25c0507149.png)

**Comment by SamuelTilly** [comment]
I'm having the same issue with pdf generated from inkscape. 
[page1.pdf](https://github.com/rkusa/pdfjs/files/5411299/page1.pdf)

**Comment by rkusa** [comment]
Thanks for the report @wjonesusna2012 and thanks @SamuelTilly for the example PDF that helped a lot! It should be fixed now.
