### ISSUE TITLE
Adding pdf js in React js project (The PDF file is empty, i.e. its size is zero bytes.)

### ISSUE THREAD

**Issue by NirikshaKamath** [rkusa/pdfjs#228]
[test_form.pdf](https://github.com/rkusa/pdfjs/files/5160379/test_form.pdf)
I have a requirement where I have to open an existing pdf in a canvas and draw resizable and draggable rectangles in the pdf and get coordinates of these rectangles drawn. 
**I am having trouble opening my pdf in the browser** and running into multiple errors.

I did not find proper examples for react code and not understanding where I am going wrong, any help would be appreciated.
I tried following in my code 

1) **Error - Error: Invalid parameter object: need either .data, .range or .url**
` 
            import React, { PureComponent } from "react";
            import pdfjsLib from 'pdfjs-dist/webpack';
            import requiredPdf from "./test_form.pdf";
           const pdf2base64 = require('pdf-to-base64');

        pdfjsLib.GlobalWorkerOptions.workerSrc =
          'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.943/pdf.worker.min.js';

         export default class PdfViewer extends PureComponent {
          constructor(props) {
          super(props);
          this.state = {
            pdf: ""
           }
         }
         componentDidMount() {
          var res = ""
          pdf2base64("./test_form.pdf")
            .then(
                (response) => {
                    this.setState({ pdf: response })
                    console.log(response); //cGF0aC90by9maWxlLmpwZw==                
                    res = response;
                }
            )
            .catch(
                (error) => {
                    console.log(error); //Exepection error....
                }
            )

        var pdfData = atob(res);
		/*
		*  costanti per i placaholder 
        */
        var maxPDFx = 595;
        var maxPDFy = 842;
        var offsetY = 7;

        var loadingTask = pdfjsLib.getDocument({ data: pdfData });
        loadingTask.promise.then(function (pdf) {
            //
            // Fetch the first page
            //
            pdf.getPage(1).then(function (page) {
                var scale = 1.0;
                var viewport = page.getViewport(scale);
                //
                // Prepare canvas using PDF page dimensions
                //
                var canvas = React.findDOMNode(this.refs.canvas);
                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;
                //
                // Render PDF page into canvas context
                //
                var renderContext = {
                    canvasContext: context,
                    viewport: viewport
                };
                //page.render(renderContext);

                page.render(renderContext).then(function () {
                    document.trigger("pagerendered");
                }, function () {
                    console.log("ERROR");
                });

            });
        });

      }

       render() {

        return (
                <div class="container">
                    <div class="row">
                        <div class="col-md-12" >
                            <button class="btn btn-primary btn-block" onClick="showCoordinates()">Show PDF Placeholders
                        Coordinates</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12" id="pdfManager" >
                            <div class="row" id="selectorContainer">
                                <div class="col-fixed-240" id="parametriContainer">
                                </div>
                                <div class="col-fixed-605">
                                    <div id="pageContainer" class="pdfViewer singlePageView dropzone nopadding"
                                    >
                                        <canvas id="the-canvas" refs="canvas"></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        );
       }
     }`

2)I tried adding the url of the file directly in the above code like this 
**Error -Unhandled Rejection (Error): PDFPageProxy.getViewport is called with obsolete arguments.**

`import React, { PureComponent } from "react";
import pdfjsLib from 'pdfjs-dist/webpack';
import requiredPdf from "./test_form.pdf";
// The workerSrc property shall be specified.
//
            pdfjsLib.GlobalWorkerOptions.workerSrc =
               'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.943/pdf.worker.min.js';

         export default class PdfViewer extends PureComponent {
           constructor(props) {
            super(props);
              this.state = {
                      pdf: ""
                             }
                   }

    componentDidMount() {
        /*
        *  costanti per i placaholder 
        */
        var maxPDFx = 595;
        var maxPDFy = 842;
        var offsetY = 7;

        var loadingTask = pdfjsLib.getDocument(requiredPdf);
        loadingTask.promise.then(function (pdf) {
            //
            // Fetch the first page
            //
            pdf.getPage(1).then(function (page) {
                var scale = 1.0;
                var viewport = page.getViewport(scale);
                //
                // Prepare canvas using PDF page dimensions
                //
                var canvas = React.findDOMNode(this.refs.canvas);
                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;
                //
                // Render PDF page into canvas context
                //
                var renderContext = {
                    canvasContext: context,
                    viewport: viewport
                };
                //page.render(renderContext);

                page.render(renderContext).then(function () {
                    document.trigger("pagerendered");
                }, function () {
                    console.log("ERROR");
                });

            });
        });

    }

    render() {

        return (
            <div class="container">
                <div class="row">
                    <div class="col-md-12" >
                        <button class="btn btn-primary btn-block" onClick="showCoordinates()">Show PDF Placeholders
                        Coordinates</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" id="pdfManager" >
                        <div class="row" id="selectorContainer">
                            <div class="col-fixed-240" id="parametriContainer">
                            </div>
                            <div class="col-fixed-605">
                                <div id="pageContainer" class="pdfViewer singlePageView dropzone nopadding"
                                >
                                    <canvas id="the-canvas" refs="canvas"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}
`

3)tried converting to base64 in different way
**Error - Unhandled Rejection (InvalidPDFException): The PDF file is empty, i.e. its size is zero bytes.**
`
          import React, { PureComponent } from "react";
            import pdfjsLib from 'pdfjs-dist/webpack';

            pdfjsLib.GlobalWorkerOptions.workerSrc =
               'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.943/pdf.worker.min.js';

            var BASE64_MARKER = ';base64,';

                   export default class PdfViewer extends PureComponent {
                   constructor(props) {
                    super(props);
                            this.state = {
                      pdf: ""
                       }
                   }

    convertDataURIToBinary(dataURI) {
        var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
        var base64 = dataURI.substring(base64Index);
        var raw = window.atob(base64);
        var rawLength = raw.length;
        var array = new Uint8Array(new ArrayBuffer(rawLength));

        for (var i = 0; i < rawLength; i++) {
            array[i] = raw.charCodeAt(i);
        }
        return array;
    }

           fileToBase64(filename, filepath) {
            return new Promise(resolve => {
            var file = new File([filename], filepath);
            var reader = new FileReader();
            // Read file content on file loaded event
            reader.onload = function (event) {
                resolve(event.target.result);
            };

            // Convert data to base64 
            reader.readAsDataURL(file);
        });
    };

    componentDidMount() {
        var res = ""

        this.fileToBase64("test_form.pdf", "./test_form.pdf").then(result => {
            console.log("called", result);
            res = result;
        });
        const pdfData = this.convertDataURIToBinary(res);

        var maxPDFx = 595;
        var maxPDFy = 842;
        var offsetY = 7;

        var loadingTask = pdfjsLib.getDocument({ data: pdfData });
        loadingTask.promise.then(function (pdf) {
            //
            // Fetch the first page
            //
            pdf.getPage(1).then(function (page) {
                var scale = 1.0;
                var viewport = page.getViewport(scale);
                //
                // Prepare canvas using PDF page dimensions
                //
                var canvas = React.findDOMNode(this.refs.canvas);
                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;
                //
                // Render PDF page into canvas context
                //
                var renderContext = {
                    canvasContext: context,
                    viewport: viewport
                };
                //page.render(renderContext);

                page.render(renderContext).then(function () {
                    document.trigger("pagerendered");
                }, function () {
                    console.log("ERROR");
                });

            });
        });

    }

    render() {

        return (
            <div class="container">
                <div class="row">
                    <div class="col-md-12" >
                        <button class="btn btn-primary btn-block" onClick="showCoordinates()">Show PDF Placeholders
                        Coordinates</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" id="pdfManager" >
                        <div class="row" id="selectorContainer">
                            <div class="col-fixed-240" id="parametriContainer">
                            </div>
                            <div class="col-fixed-605">
                                <div id="pageContainer" class="pdfViewer singlePageView dropzone nopadding"
                                >
                                    <canvas id="the-canvas" refs="canvas"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}
`

ps: please excuse the code inundation. have also attached the test pdf for reference

**Comment by rkusa** [comment]
Hi @NirikshaKamath, I am afraid that it looks like you've posted this issue in the wrong repository. I think you are talking about an issue for https://github.com/mozilla/pdf.js. Sorry for the naming confusion!
