### ISSUE TITLE
append() after pageNumber() is not working

### ISSUE THREAD

**Issue by daniel-maier** [rkusa/pdfjs#23]
Hi,

I'm using version 0.8.0 and I tried your example with the footer showing the page number and the page count concatenated with a forward slash "/".

It seems that the append after the pageNumber is not working:

footer.text({textAlign: 'center'}).pageNumber().append('/').pageCount();

It renders the page number and the page count but misses the "/".

A simple append on footer.text is working though.

Am I doing something wrong or is it bug? Any workaround on this?

Thanks a lot. By the way: great job! Well done!

**Comment by rkusa** [comment]
Thanks for reporting this issue!

It should be fixed now. I've also added `appendPageCount`, ie, you can use:

```js
.pageNumber().append('/').appendPageCount() // no space between numbers and /
// or
.pageNumber().add('/').pageCount() // space between numbers and /
```

**Comment by daniel-maier** [comment]
Thanks a lot! I tested it and it's working now :)
