### ISSUE TITLE
How can we position text?

### ISSUE THREAD

**Issue by BoxSo** [rkusa/pdfjs#231]
I want to have some whitespace at the top of the page before the text starts.
Adding text is not a problem (works like a charm), but how can we tell where the first line has to start ?

Adding BRs is not possible if you have no text fragment as i understood. An empty text seems to be ignored. So no chance to add empty lines at the top of the document?

**Comment by rkusa** [comment]
Does the solution mentioned in [this issue](https://github.com/rkusa/pdfjs/issues/229) solve your use-case?

Another option would be to position a cell via specific coords, like in this test https://github.com/rkusa/pdfjs/blob/master/test/pdfs/cell/xy.js. Subsequent text will then appear below that cell.

**Comment by BoxSo** [comment]
Thanks! That helped me!
