### ISSUE TITLE
Loop Image with Variable Cause Error Unsupported Image Type

### ISSUE THREAD

**Issue by bhumi505** [rkusa/pdfjs#238]
I have problem when adding images using variable that have dynamic value in loop. The result shows an error message "Unsupported image type", but if I use a static value variable its works.

```
for (let i = 0; i < imgData.length; i++) {
  // let imgID = 123; it works

  let imgID = imgData[i].id;
  let src = fs.readFileSync(localPath + "imgFiles/" + imgID + ".jpeg");
  let img = new pdfJs.Image(src);

  doc.image(img, {
    width: 128,
    align: "center"
  });
}
```

Thanks

**Comment by rkusa** [comment]
Hi, this sounds to me like one of the images in your `imgData` array is indeed an unsupported image type (or does not have data at all). Have you checked the exact `imgID` where it fails (assuming that `123` was just used as an example here) and tried adding that statically to the PDF document?

**Comment by bhumi505** [comment]
Yeah, I tried adding static image in my PDF document and its works. You're right after I check again those images are still in PNG enxtension. I tried adding a module to convert into JPG. Thank you
