### ISSUE TITLE
text color not working as expected

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#24]
Thanks for this nice package. I tried to use text colors in my generated pdf like described in the documentation (if I've understood correctly):

    doc.text('Example:', {size: 14, color: 0x666666});

but text color keeps black as defined in pdf.js defaults (0x000000)

What am I doing wrong?

**Comment by rkusa** [comment]
It seems to work for me. Have you used the NPM or the Github version? The NPM version was `~0.5`, but the Docs are for `1.0.0`. Since this already lead to confusion a few times, I've publish `1.0.0-alpha.1` to NPM.

**Comment by glutz** [comment]
i used the npm ~0.5 and tried a lot of different color definitions, no 
success
just installed the alpha version and try it again
thanks for the immediate reply
Günter

Am 18.05.15 um 08:16 schrieb Markus Ast:

**Comment by glutz** [comment]
installed and tested 1.0.0-alpha.1 and now it works
thanks
