### ISSUE TITLE
& Characters in PDF

### ISSUE THREAD

**Issue by rainbat** [rkusa/pdfjs#244]
Hello everybody,

I just cannot figure out, how to display a & with the pdfjs library.
I tried htmlentities etc. it just won't render ... is this an issue or is it me ?

Thanks a lot, Dominique

**Comment by rkusa** [comment]
Hi @rainbat, what font are you using? `doc.text('&')` works fine for me.

E.g. just copying

```js
const doc = new pdf.Document({ font: fonts.Helvetica })
doc.text('&')
```

into the playground editor at http://pdfjs.rkusa.st/ works fine.

**Comment by rainbat** [comment]
Thanks I'll try right away !

**Comment by rainbat** [comment]
worked perfectly !
I used:
https://rawgit.com/MrRio/jsPDF/master/fontconverter/fontconverter.html
to create our font and liked it in to the lib.

Thank you again
