### ISSUE TITLE
nested tables with different border color

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#25]
Hi Markus,
I'm using nested tables and want to have different color for the inner table borders. If I specify borderColor in the inner table it was rendered with color defined in the outer table. Is it possible to have different colors for this case? And in inner table I don't want to have vertical borders, but styles for inner table borders seems to have no effect. Is it possible to achieve this and how would it work? Example code (not complete):

    var boxFrame = doc.table({
        padding: 5,
        borderWidth: 1,
        borderColor: 0xdddddd,
        widths: ['100%']
    });

    var trOuter = boxFrame.tr({});
    tdOuter = trOuter.td();

    var boxContent = tdOuter.table({
        padding: 5,
        borderHorizontalWidth: 1,
        borderColor: 0xff0000,
        widths: ['3%', '87%', '10%']
    });
    var tr1A = boxContent.tr({});
    tr1A.td('', {fontSize: 16, color: 0xdddddd});
    tr1A.td('Datenblatt', {fontSize: 16, color: 0x000000});
    tr1A.td('gültig ab 29.12.2014', {fontSize: 7.5, color: 0x000000, textAlign: 'right'});

    var tr1B = boxContent.tr({borderWidth: 0});
    tr1B.td('', {fontSize: 9, color: 0x000000});
    tr1B.td('lorem ipsum', {font: pdfFonts.font.opensans.italics, fontSize: 9, color: 0x000000, textAlign: 'left'});
    tr1B.td('', {});

Thanks for your help
Günter

**Comment by rkusa** [comment]
The style of the nested table should now be fixed. For the vertical border, you should reset `borderWidth` to `0`, eg:

```js
var boxContent = tdOuter.table({
    borderWidth: 0,
    borderHorizontalWidth: 1,
})
```

Thanks for reporting this issue!

**Comment by glutz** [comment]
Hi,

in principal it works, thanks, now i have to check, if its possible to 
set lines only for e.g. the first (header) row, the bottom line. If you 
have a tip also for this it would be very helpful.

another thing:
same scenario than the line issue:
if you use this
tr1A.td('überreicht von ...', {});
the result is as expected:
überreicht von ...
but if you use
tr1A.td('Überreicht von ...', {}); // only the Uppercase Ü changed
the result is Überreichtvon
blank between these words is missing, the blank between von and '...' is 
correct.
Its not with Ä and Ö, its only with Ü which is really interesting.

Thanks again
Günter

-- 
Günter Lutz

Altkönigstr. 3
65843 Sulzbach / Ts.
T: 06196 6520074
M: 0163 3018651

Am 19.05.15 um 19:19 schrieb Markus Ast:

**Comment by rkusa** [comment]
This issue should be solved.

You can apply a border to a single row only, eg:

```js
table.row({ borderBottomWidth: 1 })
```

**Comment by glutz** [comment]
This works fine if you have alway the same width for bottom. In my case (same scenario as before):
    var boxContent = tdOuter.table({
        padding: 3,
        borderWidth: 0,
        borderHorizontalWidth: 0,
        borderBottomWidth: 0,
        widths: ['3%', '37%', '60%']
    });

    var tr1 = boxContent.tr({borderBottomWidth: 1.0});
    tr1.td('', {});
    tr1.td('lorem ipsum', {font: pdfFonts.font.opensans.bold, fontSize: 16, color: '0xFF0000', colspan: 2});
    var tr2 = boxContent.tr({borderBottomWidth: 0.5});
    tr2.td('', {});
    tr2.td('lorem ipsum', {font: pdfFonts.font.opensans.bold, fontSize: 9, color: '0x000000'});
    tr2.td('ipsum lorem, {font: pdfFonts.font.opensans.regular, fontSize: 9});

the result is show in the screenshot. BottomWidth decreases from 1 to 0.5 in the same row. If I change value to 0.5 as in the other row(s) it works fine again, but thats not what I expect here.

![bildschirmfoto 2015-05-20 um 14 35 20](https://cloud.githubusercontent.com/assets/4963530/7725734/a284f1b8-fefd-11e4-933b-6f0b87829f62.png)

Thanks for help.

**Comment by rkusa** [comment]
Should be fixed, thanks for reporting!

**Comment by glutz** [comment]
just tested and it works fine. Thanks for your excellent support.
