### ISSUE TITLE
Cannot Append PDF file (Invalid number at #)

### ISSUE THREAD

**Issue by gak10100** [rkusa/pdfjs#253]
I am receiving and error while appending a specific PDF file.
`{
  "type": "Error",
  "message": "Invalid number at 5: 
 (code: 10)"
}`

[license.pdf](https://github.com/rkusa/pdfjs/files/6524566/license.pdf)

**Comment by rkusa** [comment]
Thanks a lot for the example PDF! I've fixed the issue and will release a new version of pdfs later today
