### ISSUE TITLE
colspan does not work as expected

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#26]
Hi,
I need to have colspan in some rows and with different cols. Here is my example which results in a corrupt pdf:

    var boxFrame = doc.table({
        padding: 5,
        borderWidth: lines.thickness.thin,
        borderColor: colors.lines.gray,
        widths: ['100%']
    });

    var trOuter = boxFrame.tr({});
    var tdOuter = trOuter.td();

    var boxContent = tdOuter.table({
        padding: 3,
        borderWidth: lines.thickness.none,
        widths: ['3%', '7%', '80%', '10%']
    });
    // Header Row
    var tr1 = boxContent.tr({borderBottomWidth: lines.thickness.medium});
    tr1.td('>', {font: pdfFonts.font.opensans.bold, fontSize: 16, color: colors.text.gray});
    tr1.td('lorem', {font: pdfFonts.font.opensans.bold, fontSize: 16, color: colors.text.gray, colspan: 3});

    // Content Rows
    var tr2 = boxContent.tr({borderBottomWidth: lines.thickness.thin});
    tr2.td(' 1', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td('2+3', {font: pdfFonts.font.opensans.bold, fontSize: 9, colspan: 2});
    tr2.td('4', {font: pdfFonts.font.opensans.regular, fontSize: 9});
    var tr2 = boxContent.tr({borderBottomWidth: lines.thickness.thin});
    tr2.td(' 1', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td(' 2', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td('2', {font: pdfFonts.font.opensans.regular, fontSize: 9});
    tr2.td('4', {font: pdfFonts.font.opensans.regular, fontSize: 9});
    var tr2 = boxContent.tr({borderBottomWidth: lines.thickness.thin});
    tr2.td(' 1', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td('2+3', {font: pdfFonts.font.opensans.bold, fontSize: 9, colspan: 2});
    tr2.td('4', {font: pdfFonts.font.opensans.regular, fontSize: 9});
    var tr2 = boxContent.tr({borderBottomWidth: lines.thickness.thin});
    tr2.td(' 1', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td(' 2', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td('3', {font: pdfFonts.font.opensans.regular, fontSize: 9});
    tr2.td('4', {font: pdfFonts.font.opensans.regular, fontSize: 9});
    var tr2 = boxContent.tr({borderBottomWidth: lines.thickness.thin});
    tr2.td(' 1', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td(' 2', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td('3', {font: pdfFonts.font.opensans.bold, fontSize: 9});
    tr2.td('4', {font: pdfFonts.font.opensans.regular, fontSize: 9});

production without errors, but if I open the file then

![bildschirmfoto 2015-05-20 um 19 10 57](https://cloud.githubusercontent.com/assets/4963530/7731889/0138d104-ff24-11e4-86aa-d82ad94aeb56.png)

It occurs if different cols in different rows are colspan'ed, the first colspan: 3 works as expected.

**Comment by rkusa** [comment]
Should be fixed, thanks for reporting!

**Comment by glutz** [comment]
just tested and it works fine. Thanks for your excellent support.

**Comment by rafis** [comment]
Is it working? I can't manage to get it work.

**Comment by rkusa** [comment]
At least [this test](https://github.com/rkusa/pdfjs/blob/master/test/pdfs/table/colspan.js) is working. Could you show your table setup?

**Comment by rafis** [comment]
Sorry, I've found my error, I was passing single width to `widths` param of table while table had two columns (because my HTML parser was wrongly detecting column widths).

Now I need other feature, I need <tr> and <td> background color, seems only <table> supports background color.

**Comment by rkusa** [comment]
Hmm all three are meant to support background colors... I'll have a look at it
