### ISSUE TITLE
Footer 100% width (without margin)

### ISSUE THREAD

**Issue by hugodion** [rkusa/pdfjs#264]
Hi,
I have a document with a general padding of 40. Is there a way to setup a footer with 100% width of document inside of it ?
I want to place a bottom image full width on every pages.
Thanks in advance !

**Comment by rkusa** [comment]
Hi, the only approach I can think of from the top of my head would be to use a document with no padding, and wrap the whole content into a cell with a padding of `40`, e.g.:

```
  const doc = new pdf.Document({
    font:    require('./font/Helvetica'),
    padding: 0
  })
  doc.pipe(fs.createWriteStream('output.pdf'))

  doc.footer().text('Footer')

  const content = doc.cell({padding: 40})
  content.text('foo')
```

Other than that, you could also create a separate PDF as a template or "background", and set it via `doc.setTemplate(...)` (see https://github.com/rkusa/pdfjs/blob/master/docs/document.md#settemplateexternal-firstpageonly) and adjust your document's bottom padding to align with the image in the template PDF.

**Comment by hugodion** [comment]
Hi Markus ! 
The setTemplate solution works perfectly in my case.
Thanks for your time and help !  :)
Hugo
