### ISSUE TITLE
how to best draw horizontal line?

### ISSUE THREAD

**Issue by purefan** [rkusa/pdfjs#269]
Hi and thanks for pdfjs! 

Im currently doing something like `doc.text('_'.repeat(58), formatting.font.regular);` to draw a horizontal line (sort of a separator) but thinking there may be a better option, or is this how you would do it?

**Comment by rkusa** [comment]
Hi, I'd probably use an empty cell for it:

```js
doc.cell({borderBottomWidth: 1, borderBottomColor: 0x000000})
```

**Comment by purefan** [comment]
hmm... I tried that but the color is different from the one using the underscore:
![image](https://user-images.githubusercontent.com/315880/140315429-b35f3afe-e8d6-41dd-9ea1-46914fee7e6a.png)

with this code:
```
doc.cell({ borderBottomWidth: 1, borderBottomColor: 0x646464 });
doc.text('_'.repeat(58), {
        font: new pdf.Font(fs.readFileSync(`${__dirname}/Lato-Regular.ttf`)),
        size: 8,
        color: 0x646464
    });
```

I also tried with `borderBottomWidth: 0.5` thinking it just seemed darker because of thickness but to me it still looks black:
![image](https://user-images.githubusercontent.com/315880/140315752-0baf7e45-723c-4bda-a2ef-15b29e76aed4.png)

**Comment by rkusa** [comment]
Doesn't look black to me, and my color picker also thinks that it is the color you specified (`0x646464`)

**Comment by purefan** [comment]
I trust you, my screen has seen better days and I didnt think of checking with a color picker. 

I just want to say I really appreciate pdfjs and your level of support, you are really great! 

Have a good one!
