### ISSUE TITLE
is there a doc.ops example/documentation that works?

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#27]
No issue, its a question.

I have seen, that pdfjs allows to work with direct pdf ops. What i want to achieve is to integrate three (simple) draws in the pdf on multiple places in a table. Therefore it seems to be not a good decision to make this with images. I attached the three forms to aks for an example on how to create those little drawings.
![bildschirmfoto 2015-05-22 um 14 39 13](https://cloud.githubusercontent.com/assets/4963530/7770655/3468804c-0091-11e5-96aa-7b0214f3744a.png)
![bildschirmfoto 2015-05-22 um 14 38 24](https://cloud.githubusercontent.com/assets/4963530/7770657/3b7ffa2c-0091-11e5-94c2-666a44b48cb5.png)
![marked](https://cloud.githubusercontent.com/assets/4963530/7770660/428a3328-0091-11e5-9959-fdb344f703a5.png)

Do you have any idea to achieve this with doc.ops? Or if you have a source to read something about this, where can I get this information. The little example is only in the documentation, not in the test.

**Comment by rkusa** [comment]
I've extended the operation method to accept a function. This allows adding relative operations, ie, generating operations from x/y coordinates. 

As an example, a rectangle can drawn with:

```
  var ops = doc.ops()
  ops.op(0, 0, 0, 'rg') // set the color to black
  ops.op(function(x, y) {
    var height = 40
    return [x, y - height, x + 60, height, 're'] // Append a rectangle to the current path as a complete subpath
  })
  ops.op('f') // fill the path
```

You can find the complete operator reference in the [PDF Reference](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf). At page **196** you'll get an overview table that can be used to jump between the different operator categories.

**Comment by glutz** [comment]
thats great, tested it and it works like described. thanks for excellent and fast support.

**Comment by rkusa** [comment]
You are welcome!
