### ISSUE TITLE
Error: The table already has a header, add additional rows to the existing table header instead

### ISSUE THREAD

**Issue by yanickrochon** [rkusa/pdfjs#272]
I have asked [this question](https://stackoverflow.com/questions/70349880/error-the-table-already-has-a-header-add-additional-rows-to-the-existing-tabl) on Stackoverflow but, with no answer after 24 hours, I have little hope to get one, now.

So, how do one "add additional rows to the existing table header" exactly since `doc.table().header()` already returns a row, and calling `doc.table().header()` multiple times throws this error?

**Comment by rkusa** [comment]
[The error](https://github.com/rkusa/pdfjs/blob/main/lib/table.js#L175) is indeed misleading, since as you correctly said, the header already returns a row. I think it makes sense to lift this restriction an allow multiple `.header()` calls as long as there has been now `.row()` call yet.

**Comment by ProMCProgramer** [comment]
@rkusa @yanickrochon I stumbled over this issue, too, but as far as I see, there is no change within the library. Since I need the availability I still searching for an workaround. Anyone could help?

**Comment by yanickrochon** [comment]
@rkusa any update on this issue?
