### ISSUE TITLE
Incorrect Text Extraction

### ISSUE THREAD

**Issue by VrajGohil** [rkusa/pdfjs#279]
Incorrect text extracted from pdf.

Example code: https://jsfiddle.net/1zurgbsn/3/

Example PDF:  https://certotest1.s3.ap-south-1.amazonaws.com/pdfs/35b44d3f4795477c94de594b9d46c1cd.pdf

Upload the pdf on the given example. Its fails to extract word **"Certificate"**, it extracts **"Certicate"**

**Comment by rkusa** [comment]
You probably meant to report this over at https://github.com/mozilla/pdf.js/
