### ISSUE TITLE
.line doesnt include line break like expected

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#28]
just updated to the newest version and now:
var s1 = 'text1';
var s2 = 'text2';
var tr5c = tr5.td({font: pdfFonts.font.opensans.regular, fontSize: 9});
    tr5c.text(s1, {})
        .line(s2, {});
pruduced the desired table cell including the text from s1 and s2 but without expected line break before s2
Could you please help?
thanks in advance

**Comment by rkusa** [comment]
`.text()` does not add a line break automatically, you could try `tr5c.text().line(s1).line(s2)` or `tr5c.text(s1).br().line(s2)`.

From which version have you updated?

**Comment by glutz** [comment]
normally  i'm using always the newest version and updated today don't 
know the last version id but was one of the latest.

but your advice solved my issue, many thanks

**Comment by rkusa** [comment]
You are welcome!
