### ISSUE TITLE
Question .add('text', {textAlign: right})

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#29]
is textAlign possible in a .add() extension of a text object?
I tried to use this but it throws an error: ReferenceError: right is not defined
I want to know if this is possible?
otherwise I have to split the text into different columns to do the alignment which is much more work
thanks for a short advice

**Comment by rkusa** [comment]
I think your error is due to `right` not being surrounded by quotes. Anyway, the `textAlign` option does only apply to the whole text object and cannot be set to text parts individually. That is, you probably have to use a two column table.

**Comment by glutz** [comment]
ok thanks
as always i follow your advice ;)
