### ISSUE TITLE
How to consume this library in react. Not able to do it. A working example or some codesandbox link with a small example would help

### ISSUE THREAD

**Issue by sharan98727** [rkusa/pdfjs#296]

**Comment by rajanandini1999** [comment]
I am also trying to use pdf.js to render pdf files in react. I need the the same UI provided by PDF.js I am trying to using the viewer.html as part of the jsx. But how do I link it up with viewer.js

**Comment by rkusa** [comment]
In the README you'll find a link to the documentation, to a playground and a folder with a lot of small examples used for unit tests. Moving the playground into a CodeSandbox might actually be a good idea.
