### ISSUE TITLE
Table Properties

### ISSUE THREAD

**Issue by rkusa** [rkusa/pdfjs#3]
### Sizing

- [x] width (absolute, relative)
- [x] padding

## Structure

- [x] colspan
- [ ] rowspan (tracked here #16)

## Alignment

- [x] align

### Style

- [x] backgroundColor

### Border

- [x] width
- [x] color

**Comment by ambegodas** [comment]
row span is not yet implemented?

**Comment by rkusa** [comment]
Yep it is not, sorry

**Comment by ambegodas** [comment]
Is there any workaround for this? Or could you please suggest some other tool to get this done?

**Comment by rkusa** [comment]
Maybe tables inside tables... otherwise, maybe http://pdfmake.org/#/ supports rowspans

**Comment by ambegodas** [comment]
@rkusa Thanks alot.
