### ISSUE TITLE
1. Character width calculation problem with some glyphs of Cyrillic fonts. 2. Unsupported characters issue

### ISSUE THREAD

**Issue by nixoz** [rkusa/pdfjs#30]
Hi rkusa, first of all thank you for the great job and useful library.

I'm recently started to use pdfjs, and looks like i've got some issues here...

1. I think here wrong calculation for character width for character "ы"
https://www.dropbox.com/s/bkkjslefdguvf1e/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202015-06-03%2018.34.07.png?dl=0 - here you can check, how the word which finished with "ы" stuck to following word.

2. If used font have no support for the used characters(like korean) everything is destroyed like that:
https://www.dropbox.com/s/i79l1j548y7d7t2/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202015-06-03%2018.38.35.png?dl=0

are you familiar with such issues? any workarounds?

Best,
S.

**Comment by rkusa** [comment]
Could you try using the repos HEAD instead of the NPM version? I've noticed similar issues 14 days ago and already fixed it. But it is not yet published to NPM

**Comment by rkusa** [comment]
I'll close this issue for now. If the issue persists, feel free to reopen it.
