### ISSUE TITLE
Info section should be an indirect object

### ISSUE THREAD

**Issue by cesquerr** [rkusa/pdfjs#301]
The PDFs generated by pdfjs are considered as invalid by some tools (like iText) because the document information dictionary should be an indirect object based on 1.6 PDFs specifications.

I am referring to the following part:
```
	/Info <<
		/Producer (pdfjs v2.4.7 \(github.com/rkusa/pdfjs\))
		/CreationDate (D:20221122143913Z00'00')
	>>
```

**Comment by rkusa** [comment]
You are right, thanks for the report!

![Screenshot 2023-04-21 at 13 19 55](https://user-images.githubusercontent.com/409021/233626678-2ca9ee57-462f-4687-ad88-6a9b60e240e4.png)
