### ISSUE TITLE
line thickness changes in table row

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#31]
Hi,
please have a look on this

        var boxFrame = doc.table({
            padding: 5,
            borderWidth: lines.thickness.thin,
            borderColor: colors.lines.gray,
            widths: ['100%']
        });

        var trOuter = boxFrame.tr({});
        var tdOuter = trOuter.td();

        var boxContent = tdOuter.table({
            padding: 3,
            borderWidth: lines.thickness.none,
            widths: ['3%', '5%', '72%', '20%']
        });
        // Header Row
        var tr1  = boxContent.tr({borderBottomWidth: lines.thickness.medium});
        var tr1c = tr1.td({});
        // include gray triangle as image
        tr1c.image(triangle, {align: 'center', width: 8})
        // tr1.td('>', {font: pdfFonts.font.opensans.bold, fontSize: 16, color: colors.text.gray});
        var _reference1 = 'text1';
        var _reference2 = 'text2';
        var td1c        = tr1.td('', {colspan: 2});
        var td1ctxt     = td1c.text('headline', {
            font: pdfFonts.font.opensans.bold,
            fontSize: 16,
            color: colors.text.gray
        });
        var td1c        = tr1.td('', {});
        var td1ctxt     = td1c.text(_reference1, {
            font: pdfFonts.font.opensans.regular,
            fontSize: 9,
            color: colors.text.black
        }).br()
            .line(_reference2, {font: pdfFonts.font.opensans.regular, fontSize: 9, color: colors.text.black});

with this code the following result appears
![bildschirmfoto 2015-06-06 um 14 26 32]

(https://cloud.githubusercontent.com/assets/4963530/8019621/1970e360-0c58-11e5-90b5-6943c16ce4ca.png)

I do not understand what I'm doing wrong. Could you help me?
Thanks for ungoing support

**Comment by rkusa** [comment]
Is this the complete code or is there another table row following? Borders of adjacent cells are merged. If there is another row following, please provide the code for this row, too. If no, please let me know and I search for the bug at another place :-)

**Comment by glutz** [comment]
there are rows following created this way (in a loop that depends on context):

            var tr2    = boxContent.tr({borderBottomWidth: lines.thickness.thin});
            tr2.td(' ', {font: pdfFonts.font.opensans.bold, fontSize: 9});
            var td2    = tr2.td({font: pdfFonts.font.opensans.bold, fontSize: 9, colspan: 2});
            td2.text('text3')
                .br()
                .line('text4', {font: pdfFonts.font.opensans.regular, fontSize: 7})
            var tr2m = tr2.td({});
            tr2m.image(marked, {align: 'center', width: 50})

hope this helps. thanks in advance.

**Comment by rkusa** [comment]
Thanks! Should be fixed

**Comment by glutz** [comment]
is fixed. works fine. thanks a lot
