### ISSUE TITLE
how can I extract contents from a pdf

### ISSUE THREAD

**Issue by yaotengyuan** [rkusa/pdfjs#310]
When I use pdf.getOutline() to get the outline, what it returns like this:

> action:null
attachment:undefined
bold:false
color:Uint8ClampedArray(3) [0, 0, 0, buffer: ArrayBuffer(3), byteLength: 3, byteOffset: 0, length: 3, Symbol(Symbol.toStringTag): 'Uint8ClampedArray']
count:5
dest:"pdfname.indd:.103644:12898"
italic:false
items:(5) [{…}, {…}, {…}, {…}, {…}]
newWindow:undefined
setOCGState:undefined
title:"contentName"
unsafeUrl:undefined
url:null

I think I shoud get the number of page from the dest "pdfname.indd:.103644:12898", because I need the page number to display on the website.
what should I do the next?

**Comment by rkusa** [comment]
I think you posted in the wrong repo, you are probably looking for https://github.com/mozilla/pdf.js/
