### ISSUE TITLE
The add() method of the table cell text method does not respect the "textAlign" or "alignment" properties

### ISSUE THREAD

**Issue by ardentia** [rkusa/pdfjs#318]
Whenever text is being gradually added to a table cell, along with the additional `textAlign` or `alignment` properties, the text that I added does not align to the right, as I would expect.

The problem is reproduced here: https://stackblitz.com/edit/js-f1ncp7?file=index.js

As you can see, the text under the last table column is not at all right-aligned.

**Comment by rkusa** [comment]
`.add()` is indeed not changing the text alignment, you have to define it when calling `.text()`: `tr.cell().text({textAlign: 'right'})`
