### ISSUE TITLE
Units undocumented

### ISSUE THREAD

**Issue by knownasilya** [rkusa/pdfjs#32]
It's not very clear what the numbers mean, and which units to use. Is it pixels (for widths/heights)? Seems weird since 8.5"x11" = 816px * 1056px, but defaults are different.

**Comment by rkusa** [comment]
PDFs are measured in points (`1⁄72"`). The default paper size is set to A4 (210 × 297mm).
If you want the US letter size use a width of `8.5*72=612` and a height of `11*72=792`.

I think these two page sizes are mentioned in the docs, however I'll add some explanation

**Comment by knownasilya** [comment]
Thanks!

**Comment by rkusa** [comment]
Added a small section about units into the docs
