### ISSUE TITLE
Table sizing not behaving

### ISSUE THREAD

**Issue by knownasilya** [rkusa/pdfjs#33]
```js
var avery5160 = {
        table: {
          paddingTop: 36,
          paddingBottom: 36,
          paddingLeft: 15.822,
          paddingRight: 15.822,
          widths: [189, 189, 189]
        },
        row: {
          height: 72,
          padding: 0
        },
        cell: {
          height: 72,
          padding: 0
        }
      }
```

I have that and I'm trying to create a template like http://www.worldlabel.com/Pages/wl-ol875.htm

It seems like either the cells or the rows are bigger then one inch..

**Comment by rkusa** [comment]
Hmm, I think this is because of the padding being added to the size (ala CSS `box-sizing: content-box`)

**Comment by knownasilya** [comment]
Yeah I noticed the note on inheriting the padding, is there a way to disable that for the children?

**Comment by rkusa** [comment]
The padding is only applied at the cell level. Setting it at the table or row level is only for inheritance. What do you want to achieve? Something like the html cellspacing?

**Comment by knownasilya** [comment]
I want to set the margins of the document, like in that link (margins section above pricing button).

**Comment by rkusa** [comment]
Does the document padding work for this?

`new pdfjs.Document({ padding: ... })`

**Comment by knownasilya** [comment]
Ah, totally missed that. Thanks!

**Comment by rkusa** [comment]
You are welcome!
