### ISSUE TITLE
appendPageNumber shows pageCount

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#34]
If I use
var footer = doc.footer()
footer.text({ textAlign: 'right' }).appendPageNumber();

the pdf only contains the last page number on all pages. Could you please check this or give me an advice if Im doing this wrong?

**Comment by rkusa** [comment]
Should be fixed, thanks for reporting!

**Comment by glutz** [comment]
it works, thanks, but an additional remark to this: I'm not able to place pageNumber on right side and date on the left side, same line with this code:
footer.text(_createdDate, {textAlign: 'left'}).appendPageNumber({textAlign: 'right'});
can you give me an advice?
out put for pagenum in this case is always 0

**Comment by rkusa** [comment]
Should be fixed, too! However, you cannot combine text alignment left and right on the same paragraph/text object (as its also not possible in e.g. Word). I think you have to use a table for this use case. Thanks again for reporting

**Comment by glutz** [comment]
fixed, thanks a lot for your advice, your completely right

**Comment by rkusa** [comment]
You are welcome!
