### ISSUE TITLE
footer, pageNumber with Text prefix

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#35]
need your help again:
.text('Seite:_', {textAlign: 'right', font: pdfFonts.font.opensans.bold, fontSize: 9}).appendPageNumber();
works as expexted. If I replace _ after Seite with a blank then this blank does not appear in output, pageNumber is appended directly to : 
Using .add(' ') doesnt work also if included between text and pageNumber, if .add('_',color: colors.text.white) is used between those parts then the pageNumber is not shown (issue of box calculation?)

could you plz check this? Thanks in advance

**Comment by rkusa** [comment]
Trailing whitespaces are trimmed, but you could use `.pageNumber()` instead of `.appendPageNumber()`, which will add a space between the page and the preceding text.

Let me know if this works for you

**Comment by glutz** [comment]
it works like a charm
Thanks a lot!

**Comment by rkusa** [comment]
You are welcome :-)
