### ISSUE TITLE
How can I get the current page number?

### ISSUE THREAD

**Issue by nirber** [rkusa/pdfjs#42]
And further more, is it possible to know if/when the next object will be drew on the next page?

**Comment by rkusa** [comment]
Current page number: [`text.pageNumber()`](https://github.com/rkusa/pdfjs/blob/master/docs/text.md#pagenumberopts)

>  is it possible to know if/when the next object will be drew on the next page?

There is [`table.beforeBreak()`](https://github.com/rkusa/pdfjs/blob/master/test/pdfs/table/breakrow.js). But this is currently only for tables and only for content before the page break. I am also working on an equivalent function for table content right after a page break. But this is not yet ready. Other than that, there is only `doc.header()` and `doc.footer()`.

What is your use case?

**Comment by nirber** [comment]
Hi,

My use case is a long list of item in a table. Which I only want to fill the first page and stop the rendering.

**Comment by rkusa** [comment]
You could wrap the table inside a box, set the box' height to the documents inner height (height - padding) and set the `overflow` option to `hidden`:

```js
var box = doc.box({
  height: doc.style.height - doc.style.paddingTop - doc.style.paddingBottom,
  overflow: 'hidden'
})

var table = box.table({ widths: ['100%']})

for (var i = 0; i < 60; ++i) {
  table.tr().td(i)
}
```

**Comment by nirber** [comment]
Amazing - thank you

**Comment by rkusa** [comment]
You are welcome!

**Comment by KaschuY** [comment]
> Current page number: [`text.pageNumber()`](https://github.com/rkusa/pdfjs/blob/master/docs/text.md#pagenumberopts)

Does this page number method still works?
I get error: Property 'pageNumber' does not exist on type 'Text'.

**Comment by rkusa** [comment]
@KaschuY No, only available inside of a header or footer now https://github.com/rkusa/pdfjs/blob/main/docs/header.md#pagenumberfn-opts
