### ISSUE TITLE
Out of memory when using pdf as image

### ISSUE THREAD

**Issue by nirber** [rkusa/pdfjs#43]
I've used a small (50kb) PDF as image

```javascript
pdfjs.load(__dirname + '/images/e.pdf', function(err, buf) {
	img = new pdfjs.Image(buf);
}); 
```

And than...
```javascript
row.td(tdStyle).image(img, imgStyle);
```

The PDF is being generated quickly, but when I open it (acrobat) I get a message 'Out of memory'.

Any idea?

**Comment by rkusa** [comment]
Could you send me the PDF your trying to embed and the resulting PDF per email (email is shown in my Github profile)?

**Comment by rkusa** [comment]
Thanks for the email! Setting the encoding from `writeFile()` to `binary` should fix the issue.

```js
fs.writeFile(fileName, pdfString 'binary', function () { 
  console.log('saved');
});
```

Please let me know if it works

**Comment by nirber** [comment]
Solved!
Thanks again.
