### ISSUE TITLE
Question: full page background pdf within generated pdf

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#50]
hi,
just a question: is it possible (and how) to place an a4 pdf as background into a pdf document and then place some text boxes in front of this to make something like an individualization of the complete document. in detail, i want to place an individual address into an existing pdf document (or as new box over the existing document. It would be great if you have a helpful idea to resolve this with pdfjs.
thanks in advance
günter

**Comment by rkusa** [comment]
I am having the same use case. I am placing the background as follows:

```js
var image = new pdfjs.Image(buffer)
var header = doc.header()
header.image(img, {
  wrap: false,
  x: 0, y: 0,
  width: img.info.width,
  height: img.info.height
})
```

**Comment by glutz** [comment]
hi
thanks, thats exactly what I need. 
perfect
