### ISSUE TITLE
Question: Is it possible to place a text on a defined position?

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#51]
Hi,

just a question:
is it possible to place a text on a defined position? Something like this:
setPos(x,y)
text("Here I am");

Use case is that I have a background pdf (like described in a previous question) and I want to place some text on different places on top of the background without generating a lot of code overhead to position this like its used with images

Thanks for an short answer
Günter

**Comment by rkusa** [comment]
Does this help: https://github.com/rkusa/pdfjs/blob/master/test/pdfs/box/absolute.js ?

**Comment by glutz** [comment]
perfect, thanks a lot!!!

**Comment by ryanadhi** [comment]
> Does this help: https://github.com/rkusa/pdfjs/blob/master/test/pdfs/box/absolute.js ?

why this link is not accessible anymore ? Thanks

**Comment by rkusa** [comment]
@ryanadhi the link is from an older version. It can still be accessed via https://github.com/rkusa/pdfjs/blob/1.x/test/pdfs/box/absolute.js, but the API has changed since. A similar example for the most recent version would be: https://github.com/rkusa/pdfjs/blob/main/test/pdfs/cell/xy.js
