### ISSUE TITLE
Angular app - How to load font files?

### ISSUE THREAD

**Issue by ddausch** [rkusa/pdfjs#52]
I am trying to generate a client-side PDF file. I looked at examples and the like but did not find a way to read in a ttf file. It looks like the code is using an XMLHttpRequest obj but the file is bundled with the app like an image file would so not clear how I would do that. Any helpful code samples would be appreciated.

**Comment by rkusa** [comment]
Hi, does the following work for you?

```js
pdfjs.load(path, function(err, buf) {
  if (err) reject(err)
  else resolve(new pdfjs.TTFFont(buf))
})
```

**Comment by ddausch** [comment]
Hi there,
With the above code, I am getting:
fs is not defined at Scope.PDFGenerationCtrl.$scope

**Comment by rkusa** [comment]
This issue probably occurs when not using browserify. As an alternative you can create your own function from the [following code](https://github.com/rkusa/pdfjs/blob/master/lib/index.js#L26-L44):

```js
    var xhr = new XMLHttpRequest()
    xhr.open('GET', path, true)
    xhr.responseType = 'arraybuffer'

    if (xhr.overrideMimeType) {
      xhr.overrideMimeType('text/plain; charset=x-user-defined')
    } else {
      xhr.setRequestHeader('Accept-Charset', 'x-user-defined')
    }

    xhr.onload = function() {
      if (xhr.status === 200) {
        callback(null, xhr.response)
      } else {
        callback(new Error(xhr.statusText), null)
      }
    }

    xhr.send(null)
```

**Comment by ddausch** [comment]
Thanks for the follow up. I am confused about your above code snippet probably due to my own lack of knowledge. If I am working strictly on the browser side, will the XMLHttpRequest function at all. There is no server involved here.

**Comment by rkusa** [comment]
Ah sorry, did not read your issue properly. Since you don't have a server involved, `XMLHttpRequest` will not do you any good. I am, however, how you bundle your font? Do you embed as base64 encoded string or something similar?

**Comment by ddausch** [comment]
No worries. I have a set of font files of type ttf and type otf that are available to the app, similar to an image file, that are in an assets dir. Truthfully I am not sure what the appropriate next step would be. I have looked at the documentation and examples but I have not been able to figure out the approach.

**Comment by rkusa** [comment]
So you have a server that—at least—serves static files (assets)? In other words, your images still work as follows: `<img src="/assets/example.jpg"/>`?

**Comment by ddausch** [comment]
Right, it does that much at least. I am running locally for testing but we will use Amazon Web Services-S3 for Prod deployment.

**Comment by rkusa** [comment]
In this case you should be able the `XMLHttpRequest` code with the path to the font, e.g., `/assets/font.ttf`. The code will make an AJAX request to your server that serves the static files (or later to amazon s3). In the end the `pdfjs.TTFFont` can be created from the `xhr.response`.

This code 

```
    xhr.responseType = 'arraybuffer'

    if (xhr.overrideMimeType) {
      xhr.overrideMimeType('text/plain; charset=x-user-defined')
    } else {
      xhr.setRequestHeader('Accept-Charset', 'x-user-defined')
    }
```

is required to tell the browser that we are requesting the data as a plan buffer of data.

**Comment by ddausch** [comment]
Thanks for the additional info. I believe I was able to read in the font file successfully. What should I do on the last step. I call doc.render(). It looks like I have 2 options: toString() and toDataURL(). I don't think I can use toString() however. Can i use toDataURL()?

**Comment by rkusa** [comment]
```js
var pdf = doc.render()
document.querySelector('#preview').setAttribute('src', pdf.toDataURL())
```

```html
<iframe id="preview" width="100%" height="650" frameborder="0"></iframe>
```

(full example https://github.com/rkusa/pdfjs/blob/gh-pages/index.html#L103)

**Comment by ddausch** [comment]
Thanks again for your help - truly appreciated! I was able to see the 'preview' in both Chrome and Firefox but not IE 11 - any thoughts as to why - perhaps iframe suppport issues? Is there a way to just kick off a 'download' to the desktop? I did not see a way to do this within iframe. Ultimately, I have to provide a mechanism to the user to save the pdf.

**Comment by rkusa** [comment]
Yeah, the iframe approach does unfortunately not work in IE. Also open the dataurl as a page does not work. I am not sure what the best approach for IE would be, but at least [pdf.js](https://mozilla.github.io/pdf.js/) should work.

**Comment by rkusa** [comment]
Just remembered that I used a download fallback for IE somewhere. I cant find it for now, but searching for "javascript dataurl download" should yield some good results, too

**Comment by ddausch** [comment]
I am not too concerned about a preview of sorts - can live without that in IE. Let me know if u track down your download fallback though. Thanks again.

**Comment by rkusa** [comment]
Something like this probably helps for the download: https://github.com/rndme/download
