### ISSUE TITLE
Better text wrapping support

### ISSUE THREAD

**Issue by knownasilya** [rkusa/pdfjs#53]
I have the following issue, sometimes text wraps if the space is close to the border, and other times it doesn't. See the photo below

![image001](https://cloud.githubusercontent.com/assets/34726/14689727/8af0d91e-0716-11e6-99ca-2c13ad28ae5d.png)

Here's my setup:

```js
var columnWidth = 198;
      var avery5160 = {
        document: {
          width: 612,
          height: 792,
          font: fonts.openSansRegular,
          // TODO: fontSize is used for layout fixes, remove once layouts more flexible
          fontSize: 9,
          paddingTop: 36,
          paddingBottom: 36,
          paddingLeft: 15.822,
          paddingRight: 15.822
        },
        table: {
          widths: [columnWidth, columnWidth, columnWidth]
        },
        row: {
          height: 72 // 1 inch
        },
        cell: {
          paddingLeft: 7,
          width: 189.36
        }
      };
```

Looking at the docs I don't see anything about wrapping for text.

**Comment by rkusa** [comment]
Hi, I was not yet able to reproduce this issue. Are you sure that your cell sizing is correct (e.g. did a test print with a table border)? According to the photo, it looks like the table cell is a little bit wider than the label your are printing on.

**Comment by rkusa** [comment]
Feel free to reopen the issue
