### ISSUE TITLE
Inconsistent whitespace

### ISSUE THREAD

**Issue by rafis** [rkusa/pdfjs#55]
In comment you say trailing whitespace, but first `.replace(/^\s+/, '')` removing leading whitespaces too.

    // remove trailing whitespaces if white-space style is set to normal
    if (style.whiteSpace === 'normal') {
      word = word.replace(/^\s+/, '').replace(/\s+$/, '')
    }

Also there is no other options for whitespace handling. If I set for example `whiteSpace: null`, then it inserts double spaces.

**Comment by rkusa** [comment]
You are right, comment should be rephrased to `remove leading and trailing whitespace`. I am afraid that there is currently only the `normal` as a valid option for `whiteSpace`. What are you trying to achieve?

**Comment by rafis** [comment]
I need some part of text to have CSS styles applied, for example, `<p>Lorem <span style="color: #000080;">ipsum</span> dolor</p>`. My HTML parser converts it to something like this:

    var doc = new pdfjs.Document({ font: fontRegular, whiteSpace: 'normal' });
    doc.text('Lorem ').append('ipsum', { color: 0x000080 }).append(' dolor');

But words are glued together `Loremipsumdolor` and also color is not applied to second word.

**Comment by rkusa** [comment]
Should work with `.add` instead of `.append` (append is meant for appending without whitespace; API is probably best choose)

**Comment by rafis** [comment]
Thank you very much! Now almost works perfect, need to fix another case `Lorem ipsum <strong>S</strong>mith-Jones`, it converts to:

    doc.text('Lorem ipsum ').add('S', { font: fontBold }).add('mith-Jones').br();

and prints "Lorem ipsum **S** mith-Jones", but I need "Lorem ipsum **S**mith-Jones".

**Comment by rkusa** [comment]
It is `append` in this case: `add('S', { font: fontBold }).append('mith-Jones');` 🙂

**Comment by rkusa** [comment]
Feel free to reopen the issue
