### ISSUE TITLE
Merge existing documents

### ISSUE THREAD

**Issue by glutz** [rkusa/pdfjs#58]
would it be possible to add a multi-page-pdf to a pdfjs document? I try to merge some existing pages to a generated pdf document

**Comment by rkusa** [comment]
Unfortunately, this is currently not possible. However, functionality like parsing existing PDF is implemented, but when adding a PDF as image, [only the first page is used](https://github.com/rkusa/pdfjs/blob/dd7ff77d1cc5bc44a36fdc725cd1e38425eab52d/lib/image.js#L95).

**Comment by glutz** [comment]
ok, thanks for your quick reply. workaround could be to make a new page and place only the first page of a document into the generated file, as an image overview. Next question: is it possible to overwrite this function? To get all pages from the included pdf?

**Comment by rkusa** [comment]
The better approach would be to add the pages directly, instead of adding them as images into another page. A quick outline how the code could work:

```js
const pdf = doc.render()

const Parser = require('pdfjs/lib/pdf/parser/document')
const PDFFormXObject = require('pdfjs/lib/pdf/object/formxobject')
const parser = new Parser(bufferOfExistingPdf)
parser.parse()

const catalog  = parser.trailer.get('Root').object.properties
const pages    = catalog.get('Pages').object.properties.get('Kids')

const mock = {
  objects: [],
  addObjectsRecursive: PDFFormXObject.prototype.addObjectsRecursive ,
}
mock.addObjectsRecursive(pages)

mock.objects.forEach(obj => pdf.addObject(obj))

pdf.toString()
```

This is untested, but does maybe help as a starting point?

**Comment by glutz** [comment]
thanks a lot for this starting point. i try this directly. Thanks for your support, excellent as always

**Comment by rkusa** [comment]
Were you able to merge PDFs successfully?

**Comment by rkusa** [comment]
With `2.0.0-alpha.1` there is now an API for that, see [here](https://github.com/rkusa/pdfjs/blob/master/docs/document.md#addpagesoffexternal).
