### ISSUE TITLE
Are Standard 14 fonts supported?

### ISSUE THREAD

**Issue by rafis** [rkusa/pdfjs#60]
I'm recieving following error:

    TypeError: Text must have a font set or inherited
        at new module.exports (pdfjs.js:559)
        at Text.add (pdfjs.js:493)
        at new module.exports (pdfjs.js:437)
        at Container.text (pdfjs.js:92)

For example, [JSPDF](https://github.com/MrRio/jsPDF) supports Standart 14 fonts, but doesn't supports CID or AFM fonts.

**Comment by rkusa** [comment]
Unfortunately not, sorry. I understand that the standard fonts are very useful. However, since I am only using TTF fonts, I was not able to find time to implement them. But I have this one still on my list.

Refs #20

**Comment by rafis** [comment]
Strange, they are storing metrics compressed and uncompress each time:
https://github.com/MrRio/jsPDF/blob/master/plugins/standard_fonts_metrics.js
Why not to store them in regular javascript array (json)!

Yes, this is duplicate of #20, sorry.
