### ISSUE TITLE
Question can I use it with webpack and angularjs

### ISSUE THREAD

**Issue by eljaiek** [rkusa/pdfjs#64]

**Comment by rkusa** [comment]
I am using it with webpack, but not with angular. But still, should be possible

**Comment by eljaiek** [comment]
Awesome, thanks for your time
You could post  a  webpack config example, in order to I can see how to do it, because I already tried it, but when I run this code on the browser     

`  let doc = new pdf.Font(require('pdfjs/font/Helvetica.json'));
        let ext = new pdf.ExternalDocument(url);
        doc.setTemplate(ext);
        doc.addPagesOf(ext);
        doc.end(); 
`
this console error shows up "TypeError: Cannot read property '3' of undefined"
this is a portion of my webpack config
`export default new WebpackConfig().merge({

    context: SRC_FOLDER,

    node: {
        fs: "empty"
    },

    entry: {
        'pdf.worker': 'pdfjs-dist/build/pdf.worker.entry',
        'vendor': './vendor.js',
        'app': './app.js'
    },

    output: {
        path: BUILD_FOLDER,
        filename: '[name].bundle.js',
        chunkFilename: '[name].bundle.js'
    },

    plugins: [
        new webpack.optimize.OccurrenceOrderPlugin(true),
        new ExtractTextPlugin({filename: '[name].bundle.css', allChunks: true}),
        new webpack.optimize.CommonsChunkPlugin({
            name: [APP_ENTRY, PDF_WORKER_ENTRY, VENDOR_ENTRY],
            minChunks: Infinity
        }),
        new webpack.ProvidePlugin({
            "window.jQuery": "jquery",
            "$": "jquery",
            "jQuery": "jquery"
        }),
        new webpack.LoaderOptionsPlugin({
            test: /\.scss$/i,
            options: {
                postcss: {
                    plugins: [autoprefixer]
                }
            }
        }),
        new CopyWebpackPlugin([{
            from: './assets',
            to: 'assets'
        }])
    ],

    module: {
        rules: [
            {
                test: /\.js$/,
                use: [
                    { loader: 'ng-annotate-loader', options: { es6: true }},
                    { loader: 'babel-loader',  query: { presets: ['latest'] }}],
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        { loader: 'css-loader'},
                        { loader: 'postcss-loader' }
                    ],
                })
            },
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        { loader: 'css-loader'},
                        { loader: 'postcss-loader' },
                        { loader: 'sass-loader' }
                    ],
                })
            },
            {
                test: /\.(woff|woff2|ttf|eot|svg)$/,
                loader: 'file-loader?name=assets/fonts/[name].[ext]'
            },
            {
                test: /\.(json)$/,
                loader: 'file-loader?name=assets/[name].[ext]'
            },
            {
                test: /\.(png|jpg|jpeg|gif)$/,
                loader: 'file-loader?name=assets/images/[name].[ext]'
            },
            {
                test: /\.html$/,
                loader: 'raw-loader'
            }
        ]
    }
});`

**Comment by rkusa** [comment]
It actually required the usage of `babel-transform`, which I disliked a lot. So I took the opportunity to remove this requirement and make the bundle more browser friendly.

With the current master, an example webpack config can be found here: https://github.com/rkusa/pdfjs/blob/master/playground/webpack.config.js

```
        let ext = new pdf.ExternalDocument(url);
```

This one requires a ArrayBuffer as an input (a url will not work). An example of how to get an ArrayBuffer from an AJAX call can be found here https://github.com/rkusa/pdfjs/blob/gh-pages/index.html#L107-L127 (is probably also possible using the more recent `fetch` API).

```
        doc.setTemplate(ext);
        doc.addPagesOf(ext);
```

Using both for the same file does not make to mich sense. You can find a description of the methods here https://github.com/rkusa/pdfjs/blob/master/docs/document.md#addpagesoffexternal

Please let me know if this helps

**Comment by eljaiek** [comment]
Thanks for your time, i will send you a feedback as soon as possible
