### ISSUE TITLE
Text decorations like underline and strike through

### ISSUE THREAD

**Issue by atrerice** [rkusa/pdfjs#65]
Is there a way to underline a string?

**Comment by rkusa** [comment]
Since I had them on my list for a long time, I've used the opportunity to finally implement them.

`{ underline: true, strikethrough: true }` are now available in master

**Comment by barindam** [comment]
I tried with the latest version, still not working. Helvetica.json font I am using.
doc.text("Test Text",{ underline: true, strikethrough: true, fontSize: 12,color: '000000', textAlign:'left' })

**Comment by rkusa** [comment]
I haven't published a new version to NPM, yet. Have you installed from Github `npm install rkusa/pdfjs`?

**Comment by barindam** [comment]
I directly install using  npm install pdfjs --save

**Comment by rkusa** [comment]
For underline and strikethrough you'll have to use the most recent alpha release: `npm install pdfjs@2.0.0-alpha.3`
