### ISSUE TITLE
Can I use an External Document and then find/replace values inside it?

### ISSUE THREAD

**Issue by nwwells** [rkusa/pdfjs#67]
I think the question says it all... let me know if you need more details.

**Comment by rkusa** [comment]
This is currently not supported. Editing PDFs is – unfortunately – a big problem on its own.

However, the `ExternalDocument` object has a property `pages` from where you can at least navigate to all objects of the external document. But properly finding objects with text, decoding the text and executing a find and replace over it is not implemented.

**Comment by rkusa** [comment]
Since this is currently out of scope, I am going to close it for now.
