### ISSUE TITLE
Style change in single word.

### ISSUE THREAD

**Issue by gregorybrzeski** [rkusa/pdfjs#68]
Is it possible to change style in single word (no spaces) ?

In HTML that would be like: <b>foo</b><i>bar</i> so once it's rendered there is no space between the "foo" and "bar" so it's one work "foobar" just with different style for first three characters (bold) and last three characters (underline).

**Comment by rkusa** [comment]
Yes, using the [`append`](https://github.com/rkusa/pdfjs/blob/master/docs/text.md#appendtext-opts) method of a text object should work. Example: https://github.com/rkusa/pdfjs/blob/9085da918017840e7137ffe224ff163b58583e78/test/pdfs/text/append.js

(since it is not in the test, if changing the style is not working, it is bug)

**Comment by gregorybrzeski** [comment]
Tried following code in "playground" (online renderer) and it produces single word in all in "bold"

```
var doc = new pdf.Document({ font: fonts.Helvetica })

var cell = doc.cell({ paddingBottom: 0.5*pdf.cm })
cell.text({ fontSize: 48 })
.add('foo', { font: fonts.Helvetica })
.append('bar', { font: fonts.HelveticaBold })
```

**Comment by rkusa** [comment]
This is a bug, I'll investigate, thanks

**Comment by rkusa** [comment]
Should be fixed in `master`. Please let me know if it does not work for you or if you spot any other misbehaviour

**Comment by gregorybrzeski** [comment]
Works as expected now :-) Thank you.

As you have asked, one more small bug. In the example given in playground, include { font: fonts.HelveticaBold } in any of the headers. This causes text "Feature" to change to TimesRoman and not as defined HelveticaBold.

From my observations if you remove doc.footer() or move it to end of the code it solves the issue.

**Comment by rkusa** [comment]
Good find! Should be fixed now. Thanks a lot 👍
