### ISSUE TITLE
linebreak module - new changes breaking the application

### ISSUE THREAD

**Issue by sachinsawant71** [rkusa/pdfjs#74]
pdfjs has dependency on "linebreak" module. Due to recent name changes in "linebreak" module, pdfjs is not able to download the package during npm install. Hence the library is broken.

additional info - pdfjs text.js file uses "linebreak" package. It refers to it as "linebreak". The package name in package.json for linebreak is defined as "rkusa/linebreak". so package gets installed as "@rkusa/linebreak" not "linebreak" during npm install.

As a stopgap solution, I am using devongovett/linebreak package.

**Comment by rkusa** [comment]
Argh, should be fixed. Thanks for posting the issue!
