### ISSUE TITLE
Q: Can this be used to render PDFs?

### ISSUE THREAD

**Issue by clarkk** [rkusa/pdfjs#75]
Can this be used to load and render already generated PDF files?

I need to extract text from PDF files with text box coordinates etc

Have tried to use Poppler pdftohtml but it can not extract the embedded fonts so the actual size of the text boxes doesn't have the right size (width/height)

**Comment by rkusa** [comment]
> Can this be used to load and render already generated PDF files?

This is not possible, sorry!
