### ISSUE TITLE
PDF Compression

### ISSUE THREAD

**Issue by filipedeluna** [rkusa/pdfjs#80]
Is it possible to add a feature that would allow us to compress the PDF files? 

Is this feature already implemented?

Thank you!

**Comment by rkusa** [comment]
Hi, this feature is planned, but unfortunately not implemented yet

**Comment by anthlasserre** [comment]
Hi, any news on this feature?

**Comment by rkusa** [comment]
No news yet

**Comment by govindrai** [comment]
This will be a solid feature! 🙏
