### ISSUE TITLE
如何使用pdfjs

### ISSUE THREAD

**Issue by PrintingChen** [rkusa/pdfjs#85]
import Pdfjs from 'pdfjs引入之后如何使用呢？

**Comment by laedit** [comment]
If you use an `import`, you have to use the global alias:
``` js
import * as pdf from "pdfjs";
// then
let doc= new pdf.Document({ font: new pdf.Font(require("pdfjs/font/Helvetica.json")) });
```

**Comment by rkusa** [comment]
@laedit Thanks for providing the solution!

The library should be converted to es6 modules before leaving the current alpha version, which should improve the usability here (I have created an issue for that) #87
