### ISSUE TITLE
Access to inner stream

### ISSUE THREAD

**Issue by laedit** [rkusa/pdfjs#86]
I want to use your (excellent) pdf lib with a stream handling lib, but it checks that the stream passed has a `readable` property (valued to `true`).
The variable instantiated though `let doc = new pdf.Document(...);` doesn't have one since it is an anonymous class which extends `Fragment`, and I have to use `doc._doc` to retrieve the inner stream, which is far from a best practice and certainly not intended by you.

Is it possible to have either a `readable` property base on the one from `_doc` or a method like `getInnerStream` which returns `_doc`?

If that's ok I will be happy to propose a PR.

**Comment by rkusa** [comment]
Hi, you are right, having to use `_doc` is not intended. The property `readable` isn't in the documentation or am I missing something? https://nodejs.org/api/stream.html#stream_class_stream_readable

Anyway, the Document shouldn't be an anonymous class but rather something derived from `Readable  ` and not `Fragment`. I think the best solution here would be to extend the inner document's (currently at `_doc`) prototype by all methods `Fragment` provides. I am currently traveling until the end of the month, but I put it onto my todo list when I am back. I am also happy to accept a PR.

Thanks for bringing this up!

**Comment by laedit** [comment]
> The property readable isn't in the documentation or am I missing something?

It isn't in the documentation, but I've seen it used many times.
It appears that it's here only for legacy reason: https://github.com/nodejs/readable-stream/blob/master/lib/_stream_readable.js#L186

Thanks for your reply, I will try to propose a PR.
