### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by laedit** [rkusa/pdfjs#89]
in order to ease the use of your lib, at least with typescript, I have started to write the definitions (.d.ts file) of the pdfjs api.
Are you interested by hosting them here?
If not (that I would totally understand since the lib isn't in typescript 😄 ), are you ok if I add them to the [DefinitelyTyped](http://definitelytyped.org/) project (through an @types/pdfjs npm package)?

Side question, in my code I use the following table creation code:
``` js
doc.table({
    widths: ["*", "*", "*"],
    borderWidth: 1,
    padding: 5
  });
```
During my exploration of the docs and source of pdfjs I have seen that the `padding` isn't a direct option for table but is then passed to every cell created by the table.
Since it is not mentioned in the docs I was wondering if it is intended?

**Comment by rkusa** [comment]
Hi, I am fine with adding the definitions to the repo if this provides the best experience for TS users.

The padding option for tables kind of acts as the default value for its cells - the table itself does not have its own padding. So the value is used if a cell does not define its own padding value. During rendering, only the padding of a cell matters. So this is on purpose - still good question! Your question also reminds me of rethinking „*“ in the widths option.

Side question, do you have experience with whether libraries written in TS create a barrier for new contributors? I am not really enjoying writing a complex library like pdfjs in a dynamically types language, but also don’t want to put off others by using non-native JS.

**Comment by laedit** [comment]
Well, as I a coming from a typed world I am a little bit biased but I think that the overhead is minimal with typescript, for example, even will all strict checks activated, the diff between js and ts for the lexer is the following:
https://www.diffchecker.com/mba41M6y

tsconfig.json used:
``` js
{
    "compilerOptions": {
        "outDir": "./built",
        "allowJs": true,
        "target": "ES2017",
        "strict": true, /* Enable all strict type-checking options. */
        "noUnusedLocals": true, /* Report errors on unused locals. */
        "noUnusedParameters": true, /* Report errors on unused parameters. */
        "noImplicitReturns": true, /* Report error when not all code paths in function return a value. */
        "noFallthroughCasesInSwitch": true, /* Report errors for fallthrough cases in switch statement. */
    },
    "include": [
        "./lib/**/*"
    ]
}
```

So I think that even someone that have developed only in JS before will not be lost.

**Comment by rkusa** [comment]
Thanks for the comment - really interesting!
