### ISSUE TITLE
lineSpacing doesn't seems to do something

### ISSUE THREAD

**Issue by laedit** [rkusa/pdfjs#90]
Sorry to bother you again, but in the playground there is a [reference](https://github.com/rkusa/pdfjs/blob/master/playground/index.html#L31) to the `lineSpacing` option, though I haven't found any reference to it in the code and it doesn't seem to change anything.

Am I missing something or this option isn't implemented yet?

**Comment by rkusa** [comment]
Hi, you are not bothering me - your feedback is welcome! Maybe this is an old option from previous versions, I don't know from the top of my head, but will check once I am back from traveling next week.

**Comment by rkusa** [comment]
Checked again, `lineSpacing` is wrong, what I meant is probably `lineHeight`. I fixed it, good find, thanks for pointing it out! 👍
