### ISSUE TITLE
Does Not Show Some Characters Properly. (İıŞşĞg)

### ISSUE THREAD

**Issue by coderkan** [rkusa/pdfjs#97]
Hi,

Firstly thanks for this good repository. 
I have tried some characters to show in pdf, but I have encountered this issue. This is not showing properly.
Am I missing something about this issue?

```javascript
var cell = doc.cell({ paddingBottom: 0.5*pdf.cm })
cell.text('Features:', { fontSize: 16, font: fonts.HelveticaBold })
cell.text({ fontSize: 14, lineHeight: 1.35 })
  .add('-')
  .add('different', { color: 0xf8dc3f })
  .add('font', { font: fonts.TimesRoman })
  .add('styling', { underline: true })
  .add('options', { fontSize: 9 })

  cell.text('- Images (JPEGs, other PDFs)')
  cell.text('- İmge İşleme- İıŞşĞgÇç') // Added this line to playground
cell.text('- Tables (fixed layout, header row)')
cell.text('- AFM fonts && OTF font embedding (as CID fonts, i.e., support for fonts with large character sets)')
cell.text('- Add existing PDFs (merge them or add them as page templates)')
```

![resim](https://user-images.githubusercontent.com/8382599/40404881-b8dd876e-5e62-11e8-8fa0-0deb176089fb.png)

Regards...
Erkan

**Comment by coderkan** [comment]
Hi, 

Thanks for your quick reply. 
You are right, need to use own OTF/TTF font. I have tried snippet and working well.

Regards.

**Comment by rkusa** [comment]
Perfect! I should probably add this information (about the character set and OTF fonts) somewhere ...
